### ISSUE TITLE
Add support for matching delimiter blinking

### ISSUE THREAD

**Issue by ralexstokes** [kkawakam/rustyline#111]
I would like rustyline to blink the matching delimiter once I type it.  Is there any reason you see why this shouldn't work in the library? Otherwise, I can put together a pull request.

I would think to start with `()` but I don't see an immediate reason to not add `{} []`.  Perhaps it should be configurable for the user?

**Comment by gwenn** [comment]
Should be possible with `Highlighter` trait introduced in 2.0.
I will give it a try.

**Comment by gwenn** [comment]
3.0.0 released.
