### ISSUE TITLE
bind history-search-backward?

### ISSUE THREAD

**Issue by mitnk** [kkawakam/rustyline#115]
GNU readline support bind a keypress via INPUTRC like this:
```
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'
```

It would be great if rustyline support this.

Another option (for this specific function), rustyline can let users to customize the some KeyPress event, [like this one](https://github.com/kkawakam/rustyline/blob/ec773db5224e8296bb116709a29f0cb83c1f053f/src/lib.rs#L897), and provides low level APIs to manipulate prompted commands via history entries etc.

Thanks for this awesome project!

**Comment by mitnk** [comment]
To make my idea clear: Say I have 3 history items added to history:
```
1: echo 001
2: cat hi.txt
3. ps ax
```
After I run `ps ax`, I could do this:
```
>> ech<UP>  #  <-- type "ech" and press <UP> key.
```
And it could bring me `echo 001` (the first item in history).

**Comment by gwenn** [comment]
Indeed,
Currently rustyline ignores both `.inputrc` file and the [terminfo](https://stebalien.github.io/doc/term/term/terminfo/struct.TermInfo.html).
There is [linefeed](https://github.com/murarth/linefeed/blob/master/src/inputrc.rs) which supports both.
And [Haskeline](http://trac.haskell.org/haskeline/wiki/CustomKeyBindings) seems to use its own syntax.

**Comment by gwenn** [comment]
And,
rustyline does not support the `history-search-backward` and the `history-search-forward` commands (only `reverse-search-history`) but they are not difficult to implement.

**Comment by gwenn** [comment]
The last commits (ace74cc1874 and 0a909f7e104) in #103 should solve this issue.

**Comment by gwenn** [comment]
2.0 released

**Comment by dbarnett** [comment]
Thanks for resolving this! Looks like this provides a `bind_sequence` that can be used on the library but does not directly load any kind of inputrc, correct? So for a project like nushell to load inputrc for nushell/nushell#441, they would need to add some code in their project to find inputrc files and feed the config into rustyline?

**Comment by gwenn** [comment]
Yes to both.
There is no support to inputrc.
And you cannot redefine escape sequences: they are hardcoded [here](https://github.com/kkawakam/rustyline/blob/master/src/tty/unix.rs#L159).
