### ISSUE TITLE
Update dependencies.

### ISSUE THREAD

**Issue by ghost** [kkawakam/rustyline#119]
encode_unicode 0.1.3 -> 0.3.0
nix 0.5.0 -> 0.8.1

**Comment by cedenday** [comment]
Pinging @gwenn .

**Comment by gwenn** [comment]
Sorry,
I can't help you.
There is one pending [PR](https://github.com/kkawakam/rustyline/pull/117/commits/3f89a5aac17106d69a2b273e046cd7563e0245c2) which upgrades the `nix` dependency.
But none for the `encode_unicode`.
Feel free to send your own pull request.

**Comment by tormol** [comment]
I don't think there is any point in updating `encode_unicode`, because the parts of it this library uses are unchanged.

From `.travis.yml` it seems that the minimum version of Rust supported is 1.12;
When that is bumped at least 1.15 `encode_unicode` can be removed.

**Comment by gwenn** [comment]
[Indeed](https://github.com/kkawakam/rustyline/issues/17#issuecomment-299693300), encode_unicode can be removed.

**Comment by gwenn** [comment]
2.0 released
