### ISSUE TITLE
Broken Alt for Meta on Windows

### ISSUE THREAD

**Issue by akhilpai** [kkawakam/rustyline#122]
For both cmd.exe and powershell, the alt key has no effect as Meta in release 1.0.0. There are no problems with the control key, and the escape key may still be used as meta (although it cannot be held down and must be tapped before each command).

Occurs against toolchains:

stable-x86_64-pc-windows-msvc - rustc 1.19.0 (0ade33941 2017-07-17)
nightly-x86_64-pc-windows-msvc - rustc 1.20.0-nightly (582af6e1a 2017-07-19)

**Comment by gwenn** [comment]
I think it is fixed by a pending [PR](https://github.com/kkawakam/rustyline/pull/103/files#diff-581dbc32daed5e4e53732601b9f91c65R118):
```patch
-            let alt = key_event.dwControlKeyState & (LEFT_ALT_PRESSED | RIGHT_ALT_PRESSED) ==
-                      (LEFT_ALT_PRESSED | RIGHT_ALT_PRESSED);
+            let alt = key_event.dwControlKeyState & (LEFT_ALT_PRESSED | RIGHT_ALT_PRESSED) != 0;
```

**Comment by akhilpai** [comment]
Yes! It is fixed with your PR on my machine.

**Comment by gwenn** [comment]
2.0 released
