### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by blanham** [kkawakam/rustyline#123]

**Comment by freddie-freeloader** [comment]
It seems @gwenn is still doing some work on their fork. Will these changes be merged? :slightly_smiling_face:

**Comment by Marwes** [comment]
@gwenn Seems like you have done a lot of additions to this library. Are these published to crates.io? If not is there any chance they could be published (either if @kkawakam would give crates.io access or under a different name).

**Comment by gwenn** [comment]
@Marwes kkawakam added me as a collaborator. So I should be able to integrate any PR. But it means I will be my own reviewer and I don't feel able to do it, sorry.

**Comment by brendanzab** [comment]
We were just talking about the status of Rustyline [on the codespan gitter channel](https://gitter.im/codespan-rs/Lobby?at=5b153ec3b6eece791dda4138). @Marwes and I have been using rustyline on Gluon and Pikelet respectively, and have been very happy! I'd like to see some dependencies updated though, like in #119.

@gwenn Do you have publishing rights to the crate on crates.io? Just wondering if we should be forking... has anybody fired off an email to @kkawakam yet to see if everything's alright with them?

**Comment by gwenn** [comment]
@brendanzab No, I guess I don't have rights to publish on crates.io but @kkawakam said:
> I can handle pushing out new releases to crates.io

I guess all dependencies have already been updated in my branch.
I am working on tests/bug fixes/syntax highlighting but due to breaking changes, I would like to have something polish before consuming version 2.0.
I can try to make your projects build with my branch and if all works fine, merge an 2.0.0-alpha0 ?
Or try to merge non breaking changes ?

**Comment by gwenn** [comment]
For Pikelet,
```
diff --git a/Cargo.toml b/Cargo.toml
index 68575dc..eb18283 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -32,7 +32,7 @@ pretty = { version = "0.4.0", features = ["termcolor"] }
 unicode-xid = "0.1.0"

 # cli dependencies
-rustyline = { version = "1.0.0", optional = true }
+rustyline = { git = "https://github.com/gwenn/rustyline", version = "1.0.0", optional = true }
 structopt = { version = "0.2.2", optional = true }
 term_size = { version = "0.3.0", optional = true }

diff --git a/src/cli/repl.rs b/src/cli/repl.rs
index ebeb2c6..fea1b72 100644
--- a/src/cli/repl.rs
+++ b/src/cli/repl.rs
@@ -101,7 +101,7 @@ pub fn run(color: ColorChoice, opts: Opts) -> Result<(), Error> {
         match rl.readline(&opts.prompt) {
             Ok(line) => {
                 if !opts.no_history {
-                    rl.add_history_entry(&line);
+                    rl.add_history_entry(line.as_ref());
                 }

                 let filename = FileName::virtual_("repl");
```
Impacted by https://github.com/kkawakam/rustyline/issues/77

**Comment by gwenn** [comment]
For Gluon,
the `Editor` is not `Send`able anymore...
I will keep you posted when I have a fix.

**Comment by brendanzab** [comment]
Yup, I'm perfectly fine with breaking changes!

Re. crates.io - it is a little worrying to only have one person with access. 'bus factor' and all - I've been trying to add more people as co-owners to my crates just in case something ever happens to me!

**Comment by gwenn** [comment]
For gluon,
```diff
diff --git a/repl/Cargo.toml b/repl/Cargo.toml
index a99a3024..5332f986 100644
--- a/repl/Cargo.toml
+++ b/repl/Cargo.toml
@@ -32,7 +32,7 @@ structopt = "0.2"
 log = "0.4"
 env_logger = { version = "0.5", optional = true }
 lazy_static = "0.2.0"
-rustyline = "1.0.0"
+rustyline = { git = "https://github.com/gwenn/rustyline", version = "2.0.0-alpha" }
 walkdir = "2"
 codespan = "0.1.1"
 codespan-reporting = "0.1.1"
diff --git a/repl/src/repl.rs b/repl/src/repl.rs
index d584f259..b4809ef0 100644
--- a/repl/src/repl.rs
+++ b/repl/src/repl.rs
@@ -244,7 +244,7 @@ fn readline(editor: &Editor, prompt: &str) -> IO<Result<String, ReadlineError>>
         Err(err) => return IO::Exception(format!("{}", err)),
     };
     if !input.trim().is_empty() {
-        editor.add_history_entry(&input);
+        editor.add_history_entry(input.as_ref());
     }

     IO::Value(Ok(input))
```
Compiled but not tested

**Comment by gwenn** [comment]
https://github.com/kkawakam/rustyline/releases

**Comment by vinc** [comment]
Hi, I tested the latest 2.0.0-alpha on my chess engine and it works well on GNU/Linux (`x86_64-unknown-linux-gnu`), Android (`armv7-linux-androideabi`), and Windows (`x86_64-pc-windows-gnu`).

The changes required were the same: https://github.com/vinc/littlewing/commit/dd42d9a0b11997beee2e227e44a4582dbd30aad2

**Comment by gwenn** [comment]
See https://github.com/kkawakam/rustyline/issues/89#issuecomment-416029413

**Comment by gwenn** [comment]
2.0 released
