### ISSUE TITLE
Allow interrupts to be handled without reading a line

### ISSUE THREAD

**Issue by Marwes** [kkawakam/rustyline#125]
Specifically I am using `rustyline` to implement a REPL and I would like to handle `CTRL-C/SIGINT` while a command is currently running but I don't want to accept additional input until after a command has completed.

```f#
> let loop x = loop x
> loop () // Loops forever
CTRL-C
> 
```

Happy to implement this if it seems possible, though pointers on where to implement this would be appreciated.

cc @gwenn

**Comment by Marwes** [comment]
Upon closer inspection it looks like `rustyline`s signal handlers are only installed during the actual `Editor::readline` call so I believe I should be able to install my own handlers to deal with this.

**Comment by gwenn** [comment]
You are right. And I guess there is no cross platform solution.

**Comment by Marwes** [comment]
Since I only need CTRL-C I am going to try and use https://docs.rs/tokio-signal/0.1.2/tokio_signal/fn.ctrl_c.html which supposedly also works for windows.

**Comment by Marwes** [comment]
Have gotten rustyline and https://docs.rs/tokio-signal/0.1.2/tokio_signal/fn.ctrl_c.html to work independently of each other but when used together the `CTRL-C` handler does not seem to stick. Will continue to investigate.

**Comment by Marwes** [comment]
This all works for my purposes now and I don't expect anyone else trying to use the same library to encounter any problems as well (unless they do dumb mistakes like I did!).

Closing.
