### ISSUE TITLE
More flexible history save/load

### ISSUE THREAD

**Issue by netvl** [kkawakam/rustyline#127]
I would like to be able to save user input history to and load it from a database. However, the current load/save API requires using a file. It *is* kind of possible to load/save history in line-by-line fashion, but this is suboptimal - there is no method on `History` to access the underlying `VecDeque`, and there is also no way to fill it with lines without using `add()` which performs the history addition logic.

One possible solution I see would be to implement the following pair of methods:
```rust
pub fn replace_entries<I, S>(&mut self, lines: I) where I: IntoIter<Item=S>, S: Into<String> {}
pub fn entries(&self) -> impl Iterator<Item=&str> {}
```
I can do this, but will the PR be merged? I see that the repo is not very active.

**Comment by d-dorazio** [comment]
@gwenn would you be open to accept a PR to solve this issue? I can work on this if @netvl hasn't already implemented it.

**Comment by gwenn** [comment]
Hi,
Does any alternative (liner, linefeed, linenoise, linenoise-ng, haskeline,
jline3, ...) have such feature ?
Just to figure out if a smart API already exists (even if not compatible
with Rust).
Thanks.

PS: I do not feel able to merge PR. I do not master Rust. Sorry.

**Comment by netvl** [comment]
@gwenn I have taken a look at the libraries you listed and found the following:

1. Haskeline has methods to access the entire history as a list of strings, but it appears not to have bulk add features, and in general is also heavily file-centered.
2. Liner is heavily file-centered and has no API to manage history manually.
3. Linefeed does not seem to have history saving features. It allows reading the entire history, but no bulk add is possible.
4. Linenoise only has file-based API.
5. Ditto for linenoise-ng.
6. jline3 has a generic `History` interface which can be implemented by storing and loading history in any arbitrary way, though the default implementation is for files.

This is kinda surprising for me; making history management modular is such an obvious thing to me, I don't understand why it is not supported by almost all readline-like libraries out there.

**Comment by gwenn** [comment]
Ok,
What about a `Backend` trait to persist (load and save) the history entries ?
Make `Path` (or `AsRef<Path>`) implements `Backend`.
And fix `History.save/load` by passing a `&Backend`.

Or an `History` trait.
And make current implementation the default.

**Comment by luser** [comment]
I've long wanted a more flexible history solution for my shell. I currently use a bunch of hacks to share history between different open bash shells, forcing them to save and load history between each command. This mostly works, but the biggest downside is that the ordering of commands in each shell is not preserved, so up arrow sometimes produces counter-intuitive results because it will return the last command executed in any shell.

It would be nice to have something that could make this work nicely--a history that's shared among multiple running programs, but where each program has its own linear set of history entries.

**Comment by gwenn** [comment]
4 years later => #604
Feedback is welcome.

**Comment by gwenn** [comment]
5 years later => version 11.0.0 released.
