### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by mtn** [kkawakam/rustyline#134]
There are some broken links (for example, two of the links under [features](https://github.com/kkawakam/rustyline#features)). Something like [this link checker](https://github.com/tcort/markdown-link-check) might be handy! 🎈

**Comment by gwenn** [comment]
http://man7.org/linux/man-pages/man3/history.3.html / http://man7.org/linux/man-pages/man3/readline.3.html are also impacted.

**Comment by gwenn** [comment]
2.0 released
