### ISSUE TITLE
Ctrl+Left, Ctrl+Right for word skip

### ISSUE THREAD

**Issue by njaard** [kkawakam/rustyline#146]
readline and most GUI programs support Ctrl+Left and Ctrl+Right to move the cursor by a word at at time.  rustyline should also.

**Comment by gwenn** [comment]
You can define your own binding:
https://docs.rs/rustyline/2.0.0/rustyline/struct.Editor.html#method.bind_sequence
```rust
rl.bind_sequence(KeyPress:: ControlLeft, Cmd:: Move(Movement::BackwardWord(1, Word::Big)));
```

**Comment by gwenn** [comment]
Version 7.0.0 released
