### ISSUE TITLE
Publish 2.0.1

### ISSUE THREAD

**Issue by NQNStudios** [kkawakam/rustyline#147]
Hey there! I'm working on my own crate called [Da Vinci Bot](github.com/NQNStudios/davincibot) and added Rustyline as a dependency. I deploy Da Vinci Bot on my Android with Termux, but with Rustyline 2.0.0 as a dependency it won't compile. As of commit 69137f4f858d37c5bc86da31e5b1c98a34aa38f7 the bug is fixed, but I can't push Da Vinci Bot to crates.io if it has to depend on a submodule of Rustyline at the latest commit. In order to push a fixed version of my crate I need the changes in that commit published to crates as 2.0.1. If this could happen ASAP I'd be grateful!

**Comment by gwenn** [comment]
Done.

**Comment by NQNStudios** [comment]
Works great! (I love how simple that `cargo publish` can be.) Thanks!
