### ISSUE TITLE
About `Multi line mode` for lisp repl.

### ISSUE THREAD

**Issue by xieyuheng** [kkawakam/rustyline#153]
I saw the following in the README

> Features
>   Multi line mode (line wrapping)

How to use this feature ?

Is it possible to not let the readline commit text to the program,
until it see the bracket of sexp matches ?

The aim is to be able to edit the following kind of sexp :

        (let [(x 1)
              (y 2)])
           (add ...

I know chez-scheme's repl has this feature.

**Comment by xieyuheng** [comment]
Thanks for these notes

**Comment by RadicalZephyr** [comment]
It seems to me that supporting this inside of Rustyline wouldn't be that onerous if there was a helper trait with an appropriate interface to client code decide when/if a newline actually represents complete input.

This would be a nice quality of life improvement for anyone using Rustyline to write more complex applications (like programming language interpreters!).

Would you all be interested in a PR adding configurable support for this and a new Helper trait?

**Comment by xieyuheng** [comment]
I am interested.

**Comment by xieyuheng** [comment]
I did a PR for linefeed :: https://github.com/murarth/linefeed/pull/52

I hope the code there more or less provide some information about implementing the feature.
And I hope the comments there won't be a discouragement for you -- different projects are different.

**Comment by gwenn** [comment]
Would you mind looking at https://github.com/kkawakam/rustyline/issues/79#issuecomment-429076286 ?
Or the SQLite shell and https://sqlite.org/c3ref/complete.html.

**Comment by xieyuheng** [comment]
> "Multiline support is enabled by default and there is currently no way to disable it."
Would you mind answer "How do you enter a multiple line entry?"

**Comment by xieyuheng** [comment]
by "Multi-line mode" do you mean this feature: "your input will be wrapped on multiple lines when its length is greater than the width of your terminal." ?
