### ISSUE TITLE
Out-of-bound slice indexing bug in the example

### ISSUE THREAD

**Issue by Hirevo** [kkawakam/rustyline#164]
Hello,

I cloned this repository and I was playing with the example binary (but did not modify any of it) and I stumbled upon what seems to be a bug that has to do with the bracket highlighter.
I managed to have it reproducible.

## Version(s) and machine(s) tested:
Rustyline version as indicated by the Cargo.toml file is "2.1.0"
Tested on MacOS 10.14.2 and on Debian buster/sid (both are x86_64)
The MacOS's rustc was 1.30.1 and the Debian one was 1.30.0-nightly (2018-09-21)

## Steps to reproduce:
- After having built the example (I used: 'cargo build --examples'), launch the example executable
- Write '()(())'
- Press in sequence: left arrow, backspace, right arrow, backspace, backspace

## Expected behavior:
Delete the '(' and have '()(' remaining in the line buffer.

## Actual behavior:
Crashes with error code 101 saying:
thread 'main' panicked at 'index 4 out of range for slice of length 3'

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/4294633/48318892-f5a19600-e606-11e8-80f5-214c00ba1c1b.png">

Here is the complete backtrace I have:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: std::panicking::try::do_call
             at libstd/panicking.rs:326
   7: core::ptr::drop_in_place
             at libcore/panicking.rs:77
   8: <core::ops::range::Range<Idx> as core::fmt::Debug>::fmt
             at libcore/slice/mod.rs:1932
   9: <alloc::string::String as core::ops::deref::Deref>::deref
             at libcore/slice/mod.rs:2097
  10: <alloc::string::String as core::ops::index::Index<core::ops::range::RangeFull>>::index
             at libcore/slice/mod.rs:2143
  11: core::alloc::Layout::align
             at libcore/slice/mod.rs:1914
  12: rustyline::highlight::find_matching_bracket
             at src/highlight.rs:121
  13: core::num::<impl usize>::max_value
             at src/highlight.rs:81
  14: <example::MyHelper as rustyline::highlight::Highlighter>::highlight
             at examples/example.rs:52
  15: rustyline::tty::unix::PosixRenderer::new
             at src/tty/unix.rs:484
  16: rustyline::edit::State::refresh
             at src/edit.rs:118
  17: rustyline::edit::State::highlight_char
             at src/edit.rs:168
  18: rustyline::edit::State::highlight_char
             at src/edit.rs:349
  19: rustyline::readline_edit
             at ./src/lib.rs:582
  20: rustyline::readline_raw
             at ./src/lib.rs:657
  21: <rustyline::Editor<H>>::readline_with
             at ./src/lib.rs:756
  22: <rustyline::Editor<H>>::readline
             at ./src/lib.rs:728
  23: example::main
             at examples/example.rs:79
  24: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  25: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  26: macho_symbol_search
             at libpanic_unwind/lib.rs:103
  27: std::sys_common::bytestring::debug_fmt_bytestring
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  28: std::rt::lang_start
             at libstd/rt.rs:74
  29: example::init_logger

**Comment by gwenn** [comment]
Thank you for the bug report.
The culprit is `rustyline::highlight::find_matching_bracket`.
I will keep you posted.

**Comment by gwenn** [comment]
Ok,
The `MatchingBracketHighlihter` was not correctly notified.
Should be ok now.
I will try to write a unit test.

**Comment by gwenn** [comment]
3.0.0 released.
