### ISSUE TITLE
Compile against Rust Stable

### ISSUE THREAD

**Issue by kkawakam** [kkawakam/rustyline#17]
Currently we take advantage of some non-stabilized rust APIs but eventually we will want to be able to compile against Rust stable.  The below links are tracking issues that need to be closed out before we can compile against rust stable.

**Update June 6 2016:**  #38 introduced workaround changes that allowed rustyline to be compiled against rust stable (1.9.0).  These changes should eventually replaced by `Read::chars` and `encode_utf8` after they become stabilized in the standard library.
### TO-DO
- [ ] `Read::chars`
  - [rust-lang/rust Tracking Issue](https://github.com/rust-lang/rust/issues/27802)
  - replace workaround introduced in #38 (remove char_iter.rs)
- [ ] `encode_utf8`
  - [rust-lang/rust Tracking Issue](https://github.com/rust-lang/rust/issues/27784)
  - replace workaround introduced in #38 (remove encode_unicode crate)
- [x]  `str_char` 
  - [rust-lang/rust Tracking Issue](https://github.com/rust-lang/rust/issues/27754)
  - **stabilized in Rust-1.9**
- [x] `path_relative_from`
  - [rust-lang/rust Tracking Issue](https://github.com/rust-lang/rust/issues/23284)
  - **stabilized in Rust 1.7**
  - change from path_relative_from to strip_prefix was addressed in https://github.com/kkawakam/rustyline/pull/23
- [x] `vec::Drain` 
  - [rust-lang/rust Tracking Issue](https://github.com/rust-lang/rust/pull/30187)
  - **stabilized in Rust 1.6**

**Comment by pastoraleman** [comment]
Is this now complete with the changes merged from #38 ?

**Comment by kkawakam** [comment]
@pastoraleman I'm going to leave this open because we introduced some work-arounds in #38 to compile against 1.9.0 stable.  When `Read::chars` and `encode_utf8` become stabilized, they should replace the work-arounds introduced in #38.

I'll update the issue to reflect that change

**Comment by Yamakaky** [comment]
Did you consider using https://crates.io/crates/unicode-segmentation?

**Comment by gwenn** [comment]
@Yamakaky Correct me if I'm wrong, but it seems to me that the only places where this crate can be used is in Completer and "word" actions where the boundaries are specific (not conforming to unicode standard). And we still need to iterate on chars when reading the standard input stream...

**Comment by Yamakaky** [comment]
Oh, ok.
Opened https://github.com/unicode-rs/unicode-segmentation/issues/7

**Comment by jonas-schievink** [comment]
Looks like this can now be closed! :)

**Comment by gwenn** [comment]
Negative !
[Read::chars](https://github.com/rust-lang/rust/issues/27802) is still unstable.
But, `encode_unicode` can be removed ([encode_utf8](https://github.com/rust-lang/rust/issues/27784) is stabilised).

**Comment by jonas-schievink** [comment]
Oh, I see now. It compiles against stable, but there's a few workarounds/reimplementations for features that aren't yet stable.

**Comment by gwenn** [comment]
`Read::chars` has not been stabilized but removed !

**Comment by gwenn** [comment]
2.0 released
