### ISSUE TITLE
Suspend (Ctrl-Z) and Quit (Ctrl-\) not handled

### ISSUE THREAD

**Issue by birkenfeld** [kkawakam/rustyline#20]
Since rustyline removes the `ISIG` flag from the terminal, pressing Ctrl-Z or Ctrl-\ will insert a character instead of suspending/quitting the process. Especially suspend is quite essential for any CLI program.

Please consider using the default signal handling, or implementing some kind of handler for Ctrl-Z and Ctrl-\ that generates the signals.

**Comment by kkawakam** [comment]
I don't think I can use default signal handling.  I will probably implement some type of handler for C-z and C-\ so that we can reset the terminal attributes before generating the proper signals.

I am looking at GNU readline's doc and it seems like readline takes this approach.

**Comment by birkenfeld** [comment]
As far as I could see, there is a `#define` in libreadline called `HANDLE_SIGNALS` that determines if `ISIG` is cleared or not. Not sure what the default is though.

**Comment by kkawakam** [comment]
It looks like that is defined by default in http://git.savannah.gnu.org/cgit/readline.git/tree/rlconf.h so I'd be surprised if the compiled library version you are using does not have that defined.   

Looking at https://cnswww.cns.cwru.edu/php/chet/readline/readline.html#SEC44  and http://git.savannah.gnu.org/cgit/readline.git/tree/signals.c I do see that the readline's signal handler cleans up the terminal state and and then re-raises the signal.

**Comment by gwenn** [comment]
I try to handle Ctrl-Z in this [PR](https://github.com/kkawakam/rustyline/pull/30/commits/b4a9b38f15ca0ca972cb5b92367bc2200d56d0e).
But Ctrl-Z must be typed twice and can't find why...

**Comment by gwenn** [comment]
2.0 released
