### ISSUE TITLE
git-bash support?

### ISSUE THREAD

**Issue by ice1000** [kkawakam/rustyline#203]
I used this a little bit, works well under cmd.exe, great job!

However, when I try to run the program in git-bash, I didn't see the prompt (provided by `rl.readline(">> ");`) printed.
However, my `println!` beside works fine.

**Comment by ice1000** [comment]
Oops, I've just found

> Mintty (Cygwin/MinGW) is not supported

Is it planned?

**Comment by ice1000** [comment]
Closing as not an issue, but please reply if you have time :)

**Comment by gwenn** [comment]
There are at least two problems implementing the [`Term`](https://github.com/kkawakam/rustyline/blob/master/src/tty/mod.rs#L146) trait (mainly the input part):
* check [`is_stdin_tty`](https://github.com/kkawakam/rustyline/blob/master/src/tty/mod.rs#L156)
* and activate [`raw`](https://github.com/kkawakam/rustyline/blob/master/src/tty/mod.rs#L158) mode.

Under Mintty, you cannot use the Windows API anymore.
