### ISSUE TITLE
Bounding window awareness for output

### ISSUE THREAD

**Issue by dmit** [kkawakam/rustyline#204]
My use case: printing a long list of strings as a result of one command (e.g. auto-complete suggestions, `ls` output).

Problem: printing one string per line wastes screen space and moves command history out of view if there are more lines of output that there are rows in the terminal emulator displaying the program.

Possible solution: if `rustyline::Editor` exposes information about the dimensions of the current host terminal emulator, then the program can format its output to optimize screen space usage. Such as printing the strings in 2/3/however many columns can fit in any one line.

Determining the optimal splitting algorithm is left to the implementer. I just want to know how many monospace characters fit in one line of output.

**Comment by gwenn** [comment]
You want `rustyline` to return the [number of columns](https://github.com/kkawakam/rustyline/blob/master/src/tty/mod.rs#L75).
And then, in your code, use something like [tabwriter](https://crates.io/crates/tabwriter) or [prettytable](https://crates.io/crates/prettytable-rs) ?

**Comment by dmit** [comment]
That's right! `tabwriter` is my preferred choice, but allowing crates to use whatever formatting they want is the best, I think.

**Comment by gwenn** [comment]
Like [term_size](https://docs.rs/term_size/1.0.0-beta1/term_size/fn.dimensions.html).
