### ISSUE TITLE
Latest crates.io release fails to build on openbsd

### ISSUE THREAD

**Issue by kpcyrd** [kkawakam/rustyline#209]
The latest version doesn't seem to build due to the nix 0.11 dependency. The current master depends on nix 0.13 and builds successfully. Would you mind pushing a new release? :) Thanks!

**Comment by gwenn** [comment]
Current master contains breaking changes:
- Introduce `Context` which gives history access for completion/suggestion.
- Update `nix` dependency to 0.13.

I will try to release version 4.0 this week...

**Comment by kpcyrd** [comment]
Just noticed there's a 4.0.0 release. Awesome work, thanks!
