### ISSUE TITLE
Debugging output for unknown escape sequences

### ISSUE THREAD

**Issue by birkenfeld** [kkawakam/rustyline#21]
The `writeln()` in `escape_sequence` should probably be removed in released versions.

Thanks for your work on rustyline btw! Apart from the other issue I raised it works beautifully for me as a simple REPL line editor.

**Comment by gwenn** [comment]
Fixed:
https://github.com/kkawakam/rustyline/blob/master/src/tty/unix.rs#L204

**Comment by gwenn** [comment]
@kkawakam This issue can be closed.
