### ISSUE TITLE
Externally triggered prompt redraw or write above the prompt

### ISSUE THREAD

**Issue by flxo** [kkawakam/rustyline#229]
Hi,

I really struggled with the title for this issue - so let me describe what I need:

I want to write a console application that provide s some kind of command line that is *always* present at the bottom of the terminal. The text above this is updated from events happening somewhere else and have no influence on the prompt.

```
abc
def
>> asdf
```
```
abc
def
ghi
>> asdf
```
Currently the `readline` blocks and I haven't found a way to kind of interrupt that and print some lines and resume the input operation. Is that possible with rustyline? 

I got this working with `linefeed` that allows to clone a handle to the prompter that implements write and internally synchronises writing to stdout. A example is [here](https://github.com/murarth/linefeed/blob/a6fbc376b242712084ce8efeb254fc096f25c1ce/examples/demo.rs#L83-L101). 

For sure this topics gets complicated when it comes to paged display of the history etc...
Did this topic already raise in the past and if yes - what's the conclusion?

Thanks,

flxo

**Comment by gwenn** [comment]
I don't know how to do this!
I should investigate how [`python-prompt-toolkit`](https://python-prompt-toolkit.readthedocs.io/en/stable/pages/asking_for_input.html#prompt-in-an-asyncio-application) or `linefeed` do this.
I will look at your example.

**Comment by gwenn** [comment]
See similar topics:
 * #48
 * #199
 * #126

Async/non-blocking input but sync/coherent output.

**Comment by neonphog** [comment]
+1 I need this too. Looks like https://github.com/Dhole/rustylinez is trying to add this functionality, but didn't compile for me

**Comment by gwenn** [comment]
Just for reference:
- haskeline [getExternalPrint](http://hackage.haskell.org/package/haskeline-0.7.5.0/docs/System-Console-Haskeline.html#g:6)
- python prompt toolkit [patch_stdout](https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html?highlight=patch_stdout#prompt-in-an-asyncio-application) ([example](
https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/prompts/patch-stdout.py))
- replxx [print](https://github.com/AmokHuginnsson/replxx/blob/master/include/replxx.hxx#L223) ([example](https://github.com/AmokHuginnsson/replxx/blob/master/examples/cxx-api.cxx#L249))
- linefeed [write_fmt](https://docs.rs/linefeed/0.6.0/linefeed/interface/struct.Interface.html#method.write_fmt ([example](https://github.com/murarth/linefeed/blob/master/examples/demo.rs#L93))

I am not sure but I guess we should give priority to user input for example while doing completion/listing completion candidates.

**Comment by gwenn** [comment]
Could you please give #235 a try ?

**Comment by flxo** [comment]
@gwenn Thanks. I will try that!

**Comment by gwenn** [comment]
Should work on windows now.
Only tested with:
```sh
$ wineconsole --backend=curses target/x86_64-pc-windows-gnu/debug/examples/external_print.exe
```

**Comment by tailhook** [comment]
I've just got a very similar issue: I want asynchronous completion. I don't think that waiting on `<tab>` for too long makes sense as well as putting completion in front of the user if they already don't expect it.

So what I think I'm going to do is:
1. Wait 100ms in completion handler, if it's not ready put ` -- loading completions` to the hint
2. Fetch completions in background
3. Change the hint to ` -- completions loaded` (user can now press tab and that will work)

The problem is to update hint on (3). While #235 helps there if I also print a line into the external printer that line will bother users.

We can probably apply #235 which sets up some async infrastructure, and then add another pipe to signal refresh.

Alternatively, we can introduce some simple signal to refresh instead of #235, and use that as a basis for the external printer.

**Comment by vi** [comment]
Are there any updates on async and/or printing while readlining?

**Comment by JanBeh** [comment]
> Are there any updates on async and/or printing while readlining?

In the master branch, there has been support added for printing while reading, see [example](https://github.com/kkawakam/rustyline/blob/280e71191fef234c698fe1d94dedc270a6f37c33/examples/external_print.rs).

On my terminal, this appears to be buggy yet, so I filed a [bug report](https://github.com/kkawakam/rustyline/issues/629).

A longer thread on URLO: [Text-mode (terminal) application with asynchronous input/output](https://users.rust-lang.org/t/text-mode-terminal-application-with-asynchronous-input-output/74760).

**Comment by gwenn** [comment]
Version 10.0.0 released.
