### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by dignifiedquire** [kkawakam/rustyline#236]
Any chance you could do a new release, would like to use the latest fixes from `master`, without pulling in a git dependency

**Comment by gwenn** [comment]
I would like to finalize some PRs (https://github.com/kkawakam/rustyline/pull/231 and https://github.com/kkawakam/rustyline/pull/235) before a new release.
Mainly because this will be a major release (5.0.0) due to breaking changes...

**Comment by jonathandturner** [comment]
@gwenn - just to come back to this, do you know when you might publish the new version?

**Comment by gwenn** [comment]
Maybe this week-end (22-23/06).

**Comment by gwenn** [comment]
Version 5.0.0 released.
