### ISSUE TITLE
History and backspace corrupt commandline

### ISSUE THREAD

**Issue by jonathandturner** [kkawakam/rustyline#239]
With the latest rustyline, if you do the following steps, you get a corrupted input line.  You can repro this using the same app

```
cargo run --example example
```

Next, type something into one line:

```
1> this is a test file
Line: this is a test file
```

Next, press up, to get to the previous line, move the arrow to get to the word `test` and backspace to delete it.

This is what it looks like when I do this:

![Screenshot from 2019-06-09 17-24-56](https://user-images.githubusercontent.com/547158/59155361-b2939c80-8adb-11e9-82b2-eecc45f7030e.png)

Notice the line is now corrupted and is showing both the editing line and something from the previous history of the line.

**Comment by gwenn** [comment]
The highlighted/bold text is the suggestion/hint based on history.
The current implementation does not check if the cursor is at the end of the line / if the whole line matches a previous history entry.
https://github.com/kkawakam/rustyline/blob/master/src/hint.rs#L37
```rust
    fn hint(&self, line: &str, pos: usize, ctx: &Context<'_>) -> Option<String> {
...
        if let Some(history_index) =
            ctx.history
                .starts_with(&line[..pos], start, Direction::Reverse)
...
```

**Comment by gwenn** [comment]
`liner` does not display any suggestion while editing an history entry:
https://github.com/redox-os/liner/blob/master/src/editor.rs#L863
```rust
        // If we are editing a previous history item no autosuggestion.
        if self.hist_buf_valid {
            return None;
        }
```

**Comment by gwenn** [comment]
See #240

**Comment by jonathandturner** [comment]
That fix works for me, thanks!
