### ISSUE TITLE
Crash when typing before prompt is ready

### ISSUE THREAD

**Issue by jonathandturner** [kkawakam/rustyline#249]
If there is leftover text in the buffer, or you type too soon before rustyline is ready, I'm seeing that it looks like we trip over this and crash:

https://github.com/kkawakam/rustyline/blob/9d67a198167210bd0cc1458f0e64b55883a878a7/src/tty/unix.rs#L653-L658

It seems like it might be where the ansi doesn't see the correct answers coming back.

Here's what the output looks like:

![Screenshot from 2019-07-30 13-52-15](https://user-images.githubusercontent.com/547158/62094457-5118ce80-b2d1-11e9-8a06-0f435ed20632.png)

I wonder if it might be possible to clear (or maybe lock?) the input buffer before rustyline is ready, so that it doesn't interfere with rustyline getting ready to read input.

**Comment by gwenn** [comment]
Maybe related to #246 (same cause).
A quick fix would be to skip checking the cursor position if some bytes are already available in `stdin`.

**Comment by gwenn** [comment]
https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/prompt_toolkit/application/application.py#L874
```python
        # Note: only do this if the input queue is not empty, and a return
        # value has not been set. Otherwise, we won't be able to read the
        # response anyway.
```

**Comment by gwenn** [comment]
See #250

**Comment by jonathandturner** [comment]
I haven't seen this issue since the PR, so this may have fixed it.

**Comment by gwenn** [comment]
#250 also fixes a similar issue:
https://github.com/kkawakam/rustyline/issues/246#issuecomment-516768302
Thank you for your detailed report.
I will release version 5.0.1.

**Comment by gwenn** [comment]
Version 5.0.1 released

**Comment by jonathandturner** [comment]
Thank you!
