### ISSUE TITLE
Add support for PreviousCompletion

### ISSUE THREAD

**Issue by jonathandturner** [kkawakam/rustyline#257]
Using tab completion to cycle forward in the list of possible completions is a quick way to skip to completion you want. One feature that some terminals have is the ability to cycle backward (eg Windows cmd). This is helpful because if you cycle past the one you want and realize it, you can type shift-tab and go to the previous completion.

Would be great to have this ability in rustyline also.

**Comment by gwenn** [comment]
On Windows, it should be easy.
But on Unix, we have to find the escape sequence associated to a shift-tab and hope the sequence is consistent on most terminals.

**Comment by gwenn** [comment]
https://github.com/prompt-toolkit/python-prompt-toolkit/blob/c7851c09ffbfa7d06458408abee77ab6f548852d/prompt_toolkit/input/ansi_escape_sequences.py#L77
```
    '\x1b[Z': Keys.BackTab,  # shift + tab
```

**Comment by gwenn** [comment]
See #258.
I am not sure what should be done when we reach 0.
Either restore the original buffer (like when we reach the end) or go directly to the penultimate ?

**Comment by jonathandturner** [comment]
Just as one data point, Windows cmd loops around to the first suggestion and doesn't take you back to the original buffer.

**Comment by gwenn** [comment]
I chose to behave like python-prompt-toolkit.
Original buffer is restored when you press shift-tab on the first candidate.
If shift-tab is pressed again, the last candidate is displayed...
Tell me if it suits you ?

**Comment by jonathandturner** [comment]
Sure, either works just fine for me. Thanks!

**Comment by jonathandturner** [comment]
This is working great, thanks!

Out of curiosity, do you know when the next release might be that will include this?

**Comment by gwenn** [comment]
Maybe tomorrow.

**Comment by gwenn** [comment]
Version 5.0.2 released
