### ISSUE TITLE
Option to disable bell sound

### ISSUE THREAD

**Issue by vivainio** [kkawakam/rustyline#281]
The bell rings too often in Windows, when using tab completion

I am using nushell, and filed a ticket on them to disable the bell, but apparently rustyline is the culprit https://github.com/nushell/nushell/issues/446 

Rustyline could support bell-style as seen elsewhere, but option to kill that altogether from using application would be nice.

**Comment by gwenn** [comment]
Could you please give PR #282 a try ?

**Comment by vivainio** [comment]
I'm not working on nu shell, so it could be more efficient if Nu shell guys tried to integrate this new build
