### ISSUE TITLE
[Windows] Line input doesn't properly wrap

### ISSUE THREAD

**Issue by jonathandturner** [kkawakam/rustyline#286]
On Windows 10, if you start up rustyline in the terminal and type enough that the line should wrap, it will not respect the size of the terminal it's wrapping to.

In this example, I shrink the terminal window size and start typing. The input overwrites the current line before it moves to the next line:

![image](https://user-images.githubusercontent.com/547158/64469054-0b78dc80-d180-11e9-890b-4b4fde2f46be.png)

**Comment by gwenn** [comment]
The bug seems to be [here](https://github.com/kkawakam/rustyline/blob/master/src/tty/mod.rs#L168):
```rust
        if col > max_col {
```
Both `unix` and `windows` are impacted but there is no visible effect on `unix`.

**Comment by gwenn** [comment]
Should be fixed by #287

**Comment by gwenn** [comment]
Should be fixed by version 5.0.3
