### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by jonathandturner** [kkawakam/rustyline#299]
It's been a couple months since the previous rustyline release. Any sense of when the next release is coming out?

We'd even enjoy a point release since there are some bugs that were fixed recently that help a bunch.

**Comment by gwenn** [comment]
I will try to release a new version tomorrow.
And if you or someone else want to be a collaborator, please ask @kkawakam.

**Comment by gwenn** [comment]
5.0.4 released.

**Comment by jonathandturner** [comment]
Thanks!
