### ISSUE TITLE
Ctrl+L crashes in Windows with complex prompt

### ISSUE THREAD

**Issue by jonathandturner** [kkawakam/rustyline#305]
We has a nushell user report that if you Ctrl+L in Windows, rustyline will fail with 

```
Error: Io(Os { code: 87, kind: Other, message: "The parameter is incorrect." })
```

I was able to reproduce this if the prompt is sufficiently complicated (we're using starship.rs for our fancier prompts). My guess is that the amount of time it takes to clear and to draw the prompt is causing an issue for rustyline.

https://github.com/nushell/nushell/issues/1050

**Comment by gwenn** [comment]
Sorry,
Tomorrow, I will try to reproduce the bug on my Windows 7 desktop at work.

**Comment by gwenn** [comment]
While trying to install `nushell`, the `surf` dependendy failed on `stable`...
Maybe I should try to use only `starship.rs` + `rustyline` ?

**Comment by jonathandturner** [comment]
That should be enough. You can compile with just the starship feature enabled

**Comment by gwenn** [comment]
After upgrading to rust 1.39, I still have an error with the mingw/gnu compiler.
And I cannot install `msvc`...
But my boss will lend me a laptop next week.
I will keep you posted on any progress.

**Comment by gwenn** [comment]
Ok, I've just reproduced the bug on laptop. Tomorrow evening, I will try to trace.

**Comment by gwenn** [comment]
Ok,
Ctrl-L should invalidate `Layout.cursor`/`Layout.end`.

**Comment by jonathandturner** [comment]
I believe this is fixed now.

Would it be possible to do a release that includes this fix?

**Comment by gwenn** [comment]
Version 5.0.6 released.
