### ISSUE TITLE
Cursor up in multi-line mode doesn't move to the previous line

### ISSUE THREAD

**Issue by tailhook** [kkawakam/rustyline#317]
In most other shells I've used cursor keys work up and down when inside the multi-line string and only switch history on the first and last lines of that input respectively. Is there a configuration that allows that in rustyline?

**Comment by gwenn** [comment]
No.
`readline`/`editline` don't:
```
$ echo test^V^J
test
```
We need to either fix #293 or fix [edit_history_next](https://github.com/kkawakam/rustyline/blob/master/src/edit.rs#L552).

**Comment by tailhook** [comment]
Well, I couldn't implement this in terms of #293 because of a bug (reported there). But also it's harder than needed because I could only move cursor using BackwardChar/ForwardChar. It would be much nicer if we had one of the two:

1. VisibleLineUp/Down actions
2. Move the cursor to "offset"

Also, cursor position measuring is non-trivial, so it might need to be exposed somehow.

I propose to proceed this by adding four built-in actions:
1. VisibleLineUp/Down
2. ConditionalUp/Down (or find a better name) to move up or switch history

I don't want to change current Next/PrevHistory actions because I'd like to leave `Ctrl-P`/`Ctrl-N` to listing history. And vi-mode `j`/`k` to always move over visible line (the latter would be a breaking change though).

Later we can discuss what default bindings for Up/Down should be.

What do you think?

**Comment by gwenn** [comment]
Yes, I [know](https://github.com/kkawakam/rustyline/issues/317#issuecomment-571239803):
> We need to either fix #293 [...]
