### ISSUE TITLE
Unable to do Meta-Left or Meta-Right

### ISSUE THREAD

**Issue by mgattozzi** [kkawakam/rustyline#318]
The current implementation of [`KeyPress`](https://docs.rs/rustyline/6.0.0/src/rustyline/keys.rs.html#26) only allows Meta to take a `char` rather than another `KeyPress`, which also has a `KeyPress::Char(char)` variant, and as such it disallows multi char control sequences. On OSX if one wishes to implement Ctrl+Left or Ctrl+Right functionality for a terminal shell the equivalent is Meta+Left and Meta+Right as the prior functionality is bound to switching workspaces.

Would having it take a `KeyPress` be reasonable? I see that things like `KeyPress::ControlLeft` exist but this seems less flexible rather than allowing some command modifier taking another `KeyPress` or multiple of them. Maybe I'm missing some architectural choice as to why it is this way, but I couldn't find anything in the issues or git log that would help me figure out why and have probably overlooked something here.

**Comment by gwenn** [comment]
I guess it is for historical reason: see [linenoise keys](https://github.com/antirez/linenoise/blob/master/linenoise.c#L153) 
Also see #121.
And [python-prompt-toolkit special keys](https://python-prompt-toolkit.readthedocs.io/en/master/pages/advanced_topics/key_bindings.html#list-of-special-keys)

On macOs (iterm2), typing meta-letf (Esc + Left) gives:
```
$ [D
```
On Archlinux VM, typing meta-left moves to the start of word.

**Comment by gwenn** [comment]
Just for reference:
* [termion/liner](https://docs.rs/termion/*/termion/event/enum.Key.html)
* [mortal/linefeed](https://docs.rs/mortal/*/mortal/terminal/enum.Key.html)
* [crosterm](https://docs.rs/crossterm/*/crossterm/event/struct.KeyEvent.html)

**Comment by jonathandturner** [comment]
I think meta-left/meta-right works in macOS for linefeed.

**Comment by gwenn** [comment]
`Alt+Left`works in macOS for linefeed (and rustyline).
But not `Esc+Left`: the combination is interpreted as a single `Left` by linefeed.

**Comment by gwenn** [comment]
By default, both Terminal.app and iTerm2.app are configured to sent `Esc-b` when Alt+Left are pressed...

**Comment by thomcc** [comment]
Hmm, my iTerm does `\e\e[D`/`\e\e[C` for alt+l/r. Still annoyingly non-standard, but not as bad. This follows what's listed in https://invisible-island.net/ncurses/terminfo.src.html for `iTerm2.app` (Surprised there's even an entry there -- iTerm sets its TERM variable to xterm-256color)

That said, Terminal.app does behave as you describe for me (`\ef`/`\eb`). Anyway that PR fixes this for me, I still need to make sure it doesn't break anything, I don't think escape parsing was covered by tests?

**Comment by gwenn** [comment]
From a Windows perspective, it makes sense to separate key code and modifiers.
But from a Unix perspective, we would not be able to report a Ctrl-Alt-Shift-M...

**Comment by thomcc** [comment]
Not entirely true, see: https://github.com/kkawakam/rustyline/pull/333/files#diff-0655ced7de6892bafa1f0000619c718eR327-R330 (and linked page).

In practice I think terms tend to only send meta or alt though, and so that code just treats any Meta/Alt presses it gets the same. I think you're right for non-special keys though.

(Also, I think this issue is about either)

**Comment by gwenn** [comment]
Version 7.0.0 released
