### ISSUE TITLE
Highlighter::highlight_char doesn't distinguish between edits and cursor movement

### ISSUE THREAD

**Issue by thomcc** [kkawakam/rustyline#332]
The `highlight_char` docs say: "Tells if `line` needs to be highlighted when a specific char is typed or when cursor is moved under a specific char".

I'm reading this to mean it's called both on cursor movement and on line edits, but I don't think there's a way to tell which is happening in the current API. For my use case, line edits require re-style, but cursor movements generally would not...

**Comment by gwenn** [comment]
Indeed, currently you cannot make the distinction.
`highlight_char` was introduced to avoid refreshing the whole line except when you type (or move on) a specific char (like ')' to highlight the matching pair).

**Comment by thomcc** [comment]
This seems unfortunate, as a lot of cases would only need to repaint when the text changes, and not on movement.

**Comment by gwenn** [comment]
```rust
pub trait Highlighter {
...
    /// Due to current limitations (no incremental parsing, no partial repaint, flickers),
    /// `Hightlighter::highlight` is not called when a character is inserted at the end of the line.
    /// If you want highlighting to be updated each time a character is typed, just overwrite this method.
    fn highlight_while_typing(&self) -> bool {
        false
    }
}
```
?

**Comment by thomcc** [comment]
Yes, although I'm realizing the larger issue is the repainting/rehighlighting on every change...
