### ISSUE TITLE
Regression: line wrap

### ISSUE THREAD

**Issue by gwenn** [kkawakam/rustyline#350]
To reproduce,
* open a terminal with limited width / columns
* type a long line until you reach the end of the screen and line wraps
* then press delete until the cursor is back at the end of the screen <= the line now is duplicated

I guess this change is the cause of the regression: https://github.com/kkawakam/rustyline/pull/338/files#diff-0655ced7de6892bafa1f0000619c718e

**Comment by gwenn** [comment]
On unix: e7bf901 is ok but 148e1ee is broken.

**Comment by thomcc** [comment]
It's also broken if you use the validator to allow line continuation.

**Comment by gwenn** [comment]
I would like to unit test this bug before any fix.

**Comment by gwenn** [comment]
While testing version 6.0.0 on different terminals (I have only one laptop, a mac and some light VMs):
* iTerm2 => OK
* Apple Terminal => OK
* Alacritty => OK
* VirtualBox + Linux console => KO
* VirtualBox + ssh => KO
If I manage to find a fix, I will need your help to test on other BSD/Linux platforms / terminals.

**Comment by thomcc** [comment]
Might be caused by terms that indicate `eat_newline_glitch` in terminfo.

Note that using validator and line continuation is broken on all terminals i've tried including iterm2/apple term. Might be a different bug.

**Comment by gwenn** [comment]
@tailhook Would you mind if I rollback your [PR](https://github.com/kkawakam/rustyline/pull/338) until we can fix it ?

**Comment by gwenn** [comment]
See https://github.com/kkawakam/rustyline/compare/master...gwenn:tty_tests?expand=1
Once #338 reverted, I will fix `compute_layout` and assertions.
