### ISSUE TITLE
Windows line wrap doesn't linefeed

### ISSUE THREAD

**Issue by AE9RB** [kkawakam/rustyline#351]
Both V6 and V5 show this behavior in Windows. It works fine in Linux. Run an example and type past the end of the line; you'll be typing over the first line. Backspace past the start of a line and the input starts moving up the screen. Reproduces in PowerShell and CMD in the old terminal (conhost.exe), new Windows Terminal, and VSCode terminal.

**Comment by gwenn** [comment]
Indeed,
At least versions 4, 5 and 6 are impacted (repaint / refresh is buggy).
And latest panics !
I don't have access to a windows machine at home and only limited access at work.
I may be able to reproduce with [Wine](https://www.winehq.org).
Regards.

**Comment by gwenn** [comment]
I cannot reproduce with Wine. But I will try to debug and fix it on Windows.

**Comment by gwenn** [comment]
Could you please confirm that it happens only on Windows 10 ?
Currently `rustyline` is using `ENABLE_WRAP_AT_EOL_OUTPUT` (which is activated by default).
And there seems to be a bug when you mix both `ENABLE_WRAP_AT_EOL_OUTPUT` and `ENABLE_VIRTUAL_TERMINAL_PROCESSING`: https://github.com/microsoft/terminal/issues/349
Before Windows 10, `ENABLE_VIRTUAL_TERMINAL_PROCESSING` is not supported so we are not impacted.

**Comment by gwenn** [comment]
As a temporary/dirty workaround, you can disable colors (`ColorMode::Disabled`) to make line wrapping works on Windows 10.

**Comment by gwenn** [comment]
Should be fixed in 6.1.2
