### ISSUE TITLE
Release plans?

### ISSUE THREAD

**Issue by dubiousjim** [kkawakam/rustyline#353]
Hi I'm contributing to a project [Deno](https://github.com/denoland/deno) that uses rustyline and nix. We're importing nix 0.14 because that's what rustyline 6.0.0 does. (And if we use a different version of nix than the one used by the rustyline we're using, some of our Error conversions get messed up.)

I see that you upgraded to nix 0.17 already in your master branch, back on Feb 8. What is your thinking about when you will cut a new release that might include that?

**Comment by gwenn** [comment]
There is at least [one](#350) regression that I would like to fix.
This regression was introduced by a PR with a breaking change.
So maybe we should try to release a 6.Y.Z version without this PR ?

**Comment by dubiousjim** [comment]
Ok, thanks. That at least helps me to know which rev to depend on for development.

**Comment by dubiousjim** [comment]
In fact, it would be useful to our project if you could make a release soon that included the upgrade to depending nix 0.1.7. Is that doable?

You're best placed to know what other commits post-6.0.0 should be in it.

**Comment by gwenn** [comment]
I will try to make a release tomorrow.

**Comment by dubiousjim** [comment]
Super, thanks!

**Comment by gwenn** [comment]
Version 6.1.0 is available.

**Comment by dubiousjim** [comment]
Thanks again!
