### ISSUE TITLE
Does clearing screen reset background also

### ISSUE THREAD

**Issue by jonathandturner** [kkawakam/rustyline#366]
Recently, we had someone file this issue for nushell: https://github.com/nushell/nushell/issues/1599

It seems as though when they use the clear screen shortcut, rustyline is able to clear the screen. But, when there's a background color (like the red we use for errors), that doesn't get cleared.

Is there a way to enable clearing the background also?

**Comment by bjorn3** [comment]
Unix uses `\x1b[H\x1b[2J` which clears the background:

https://github.com/kkawakam/rustyline/blob/cbedcf1df1905840deae4463bf060e6015c341f6/src/tty/unix.rs#L656

Windows uses `FillConsoleOutputCharacterA` to fill the screen with spaces. It seems that this doesn't affect colors. According to https://docs.microsoft.com/en-us/windows/console/clearing-the-screen you need to call `FillConsoleOutputAttribute` as well.

https://github.com/kkawakam/rustyline/blob/d95cd7c75a0111012e387612f885165e8abf0498/src/tty/windows.rs#L292-L298

**Comment by gwenn** [comment]
Indeed, we should do both like
- [Haskeline](https://github.com/judah/haskeline/blob/master/System/Console/Haskeline/Backend/Win32.hsc#L562)
- [Linefeed](https://github.com/murarth/mortal/blob/master/src/windows/terminal.rs#L880)
- [python-prompt-toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/prompt_toolkit/output/win32.py#L257)

**Comment by gwenn** [comment]
Could you please give a try to PR #367 ?
Thanks.

**Comment by jonathandturner** [comment]
Yes, this looks better. I couldn't get it to repro for the things I tried.

**Comment by jonathandturner** [comment]
@gwenn - can we merge this fix for the next release, too?

**Comment by gwenn** [comment]
@jonathandturner 6.1.2 has been published.
