### ISSUE TITLE
Support Windows platform

### ISSUE THREAD

**Issue by gwenn** [kkawakam/rustyline#37]
https://www.reddit.com/r/rust/comments/4jufvh/which_readlinelike_crate/d3afuv8
> I really wish there was a readline-like library which worked for windows as well.

**Comment by kkawakam** [comment]
@gwenn I'm gonna start taking a look at this if you don't mind.  Going to refer to https://github.com/MSOpenTech/redis/tree/3.0/deps/linenoise which is the windows port of linenoise.

**Comment by gwenn** [comment]
I don't have access to a Windows machine and I tried Windows VM without success.
And there is another fork with windows support here:
https://github.com/arangodb/linenoise-ng
Regards.

**Comment by kkawakam** [comment]
Partial support added in #42.  Rust's stdio module for Windows uses the ReadConsoleW from winapi which does not seem to capture modifier keys (CTRL or ALT).  Some additional work needs to be done to instead use the ReadConsoleInputW in winapi to support the same operations as we do in Linux

**Comment by Marwes** [comment]
@kkawakam History (pressing up arrow) does not work on Windows but I assume this is for the same reason as CTRL and ALT?

**Comment by kkawakam** [comment]
@Marwes that is probably the case, you should probably continue using linenoise-rs for support on windows.  I am still working on full windows support right now and hopefully I'll have that out this week.

**Comment by gwenn** [comment]
Ok,
Don't take me wrong but...
I started to look at Windows support by using [Wine](https://www.winehq.org) and cross compiling.
 * refresh screen:
https://github.com/gwenn/rustyline/blob/master/src/lib.rs#L192
 * clear screen:
https://github.com/gwenn/rustyline/blob/master/src/lib.rs#L416
 * console input:
https://github.com/gwenn/rustyline/blob/master/src/lib.rs#L959

I am also looking at [this](https://github.com/DanielKeep/rust-ansi-interpreter) project to support ANSI escape sequence on Windows.

If it looks good to you, I can take some time to merge and send a pull request.
Regards.

**Comment by kkawakam** [comment]
@gwenn that is totally fine with me.  The only thing is that I would rather want to this platform specific stuff to live outside of lib.rs (kinda following the pattern we see in rust's std lib).  

Also can I add you as a collaborator, I don't have as much time to work on this at this moment and I don't want to really block your progress.

**Comment by gwenn** [comment]
@kkawakam Yes, I will try to move platform specific stuff in the `tty` module. And I don't know what Wine is emulating. There is no hurry. Take your time.

**Comment by Marwes** [comment]
Is there anything blocking a crates.io release with the windows support that works now? Minor testing on the current master seems to work well at least.

Pinning cargo to a revision works fine at the moment but it prevents publishing off libraries which depend on it as git dependencies are not allowed on crates.io.

Mainly running Windows so if there is something I can help test I'd be happy to (not very familiar with the actual Windows API however).

**Comment by kkawakam** [comment]
@Marwes I'm gonna push out a release this week, just gonna additional light testing before pushing it out to crates.io

**Comment by kkawakam** [comment]
@Marwes Sorry about the delay, I pushed out a new release (1.0.0)
