### ISSUE TITLE
Vi: Delay when switching from insert mode to normal mode

### ISSUE THREAD

**Issue by homburg** [kkawakam/rustyline#371]
When in Vi mode and switching from insert mode to normal mode there's a 500 ms delay by default.

In bash and zsh shell there's no delay on switching. What is the reason for the current delay?

I'm running [nushell](https://github.com/nushell/nushell) with a patched version of rustyline without delay: https://github.com/homburg/rustyline/commit/810be16fe4dc14b0830d5311bc099d2b3bfa73d5 It seems to be working.

**Comment by gwenn** [comment]
https://github.com/kkawakam/rustyline/blob/master/src/tty/unix.rs#L389
https://github.com/kkawakam/rustyline/blob/master/src/config.rs#L386
You don't need a patch, you just need to do (order matters):
```rust
        .edit_mode(EditMode::Vi)
        .keyseq_timeout(0) -- depends on how much your terminal is responsive
```

**Comment by homburg** [comment]
Thanks you for the response.

My right key still works perfectly in insert mode with a timeout of `0`.

I'll have to suggest a configuration option or a smaller default timeout in nushell, thanks!
