### ISSUE TITLE
Handle cursor when completing

### ISSUE THREAD

**Issue by finga** [kkawakam/rustyline#375]
I am wondering if there is the possibility to control the cursor when completing.

For example I have following input with the cursor not at the end:
```
hel
 ^ cursor after h
```

When the tuple returned by `complete()` its result can be either `Ok((0, ["help"]))` or `Ok((1, ["elp"]))`. In both cases the resulting line is `helpel`. I would like to have the possibility to have a resulting line like `help`.

**Comment by gwenn** [comment]
You should be able to do what you want by overloading [Completer::update](https://docs.rs/rustyline/6.1.2/rustyline/completion/trait.Completer.html#method.update).
It would have been easier if the last argument was the chosen `Candidate`.

**Comment by finga** [comment]
Thank you @gwenn, that works well for me.
