### ISSUE TITLE
Windows tab completion of files and dirs

### ISSUE THREAD

**Issue by fdncred** [kkawakam/rustyline#382]
I was looking at the completion code trying to figure out what would need to change so that it works better on Windows. Rustyline seems to do well with case sensitive completions but not as well on Windows where case insensitive is needed.

I was thinking this may be where the code needs to change but I could be reading this all wrong.
https://github.com/kkawakam/rustyline/blob/e7bf9012197717bbaad5f75ed91583886d906038/src/completion.rs#L338

As an example, I'd like to autocomplete `C:\Apps` by typing `cd c:\ap<tab>` but since it's case sensitive. Or vice-versa, if my folder is called `C:\apps` and I type `CD C:\A<tab>` I'd like it to autocomplete.

Is changing to case insensitive an option via configuration somehow that I have missed perhaps? Or is the only way with a PR?

**Comment by gwenn** [comment]
No, there is no option to make completion case-insensitive.

**Comment by fdncred** [comment]
Is that line the appropriate place to make a case insensitive change?

**Comment by gwenn** [comment]
I think so.
At least `macos` and `windows` are case insensitive.

**Comment by fdncred** [comment]
Wait a second, I'm primarily a user on `windows` but also use it on `macos`. I was considering a PR because it is case sensitive in Windows. MacOs works great. Are you saying that Windows implementations should already be case insensitive?

**Comment by gwenn** [comment]
I should have said:
At least `macos` and `windows` _should be_ case insensitive.
