### ISSUE TITLE
`vi_insert` should allow history traversal

### ISSUE THREAD

**Issue by lightclient** [kkawakam/rustyline#385]
It seems strange to require `EditMode::Vi` users to switch to command mode, just to pull up previous commands. I propose the following match cases are added to `vi_insert`.

```rust
KeyPress::Ctrl('N') => Cmd::NextHistory,
KeyPress::Ctrl('P') => Cmd::PreviousHistory,
```
Alternatively, these could be `Cmd::Line{Up|Down}OrNextHistory` if that's the consensus on #343.

I'm happy to submit this as a PR if it will be accepted.

**Comment by gwenn** [comment]
It seems to be the default / correct behaviour of `bash` shell: `^P`/`^N` is inserted instead !
But I am ok to fix it.

**Comment by bjorn3** [comment]
Zsh supports ctrl-p and ctrl-n for history navigation.

**Comment by lightclient** [comment]
> It seems to be the default / correct behaviour of `bash` shell: `^P`/`^N` is inserted instead !
> But I am ok to fix it.

Interesting, where are you seeing this? [I am seeing](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Commands-For-History) that `C-p` and `C-n` should perform "previous-history" and "next-history" respectively.

**Comment by gwenn** [comment]
> Interesting, where are you seeing this? [I am seeing](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Commands-For-History) that `C-p` and `C-n` should perform "previous-history" and "next-history" respectively.

I guess that page refers to emacs mode...

**Comment by lightclient** [comment]
Ah, you're right! My fault. Hmm, in that case it probably is best to not deviate from standard bash. Is there a way we could expose the option of different bindings? E.g. in bash, we could modify the keymap.

**Comment by gwenn** [comment]
Currently, [custom key bindings](https://docs.rs/rustyline/6.1.2/rustyline/struct.Editor.html#method.bind_sequence) apply to all modes. So you should be able to do:
```rust
    rl.bind_sequence(KeyPress::Ctrl('N'), Cmd::NextHistory);
    rl.bind_sequence(KeyPress::Ctrl('P'), Cmd::PreviousHistory);
```

**Comment by lightclient** [comment]
Great, I will look into use this instead. Thank you.
