### ISSUE TITLE
Two-line prompts not respected

### ISSUE THREAD

**Issue by lightclient** [kkawakam/rustyline#390]
It seems like when a prompt is more than one line, the list of autocompletions is cutoff. See the following image for an example. Left is with a two line prompt, right is a one line prompt.

![2020-05-20-1590005856_screenshot_1920x1080](https://user-images.githubusercontent.com/14004106/82493245-e07fb000-9aa4-11ea-9d1f-9b0a2220605c.jpg)

In both cases, I doubled tapped tab after typing `vim abc`. Only the one line prompt properly displayed the potential completions in the directory.

**Comment by gwenn** [comment]
Also buggy with multiline input.

**Comment by gwenn** [comment]
@lightclient Could you please give PR #392 a try ?

**Comment by lightclient** [comment]
@gwenn I'm still having issues after patching it into `nushell` `0.14.0` (see [here](https://github.com/lightclient/nushell/tree/rl-buggy-multiline-prompt)).

**Comment by gwenn** [comment]
@lightclient Would you mind testing with rustyline example first ?
```patch
diff --git a/examples/example.rs b/examples/example.rs
index 2b3363f..916ba9c 100644
--- a/examples/example.rs
+++ b/examples/example.rs
@@ -102,7 +102,7 @@ fn main() -> rustyline::Result<()> {
     }
     let mut count = 1;
     loop {
-        let p = format!("{}> ", count);
+        let p = format!("{}\n> ", count);
         rl.helper_mut().expect("No helper").colored_prompt = format!("\x1b[1;32m{}\x1b[0m", p);
         let readline = rl.readline(&p);
         match readline {
```
```
rustyline % cargo run --example example
1
> target/debug/deps/libd
libdirs_next-b7bba4783d9fc177.rmeta      libdirs_sys_next-5fc98097bfbb9d7c.rmeta  libdirs_next-b7bba4783d9fc177.rlib
libdoc_comment-d8fc5586c1f80845.rlib     libdirs_sys_next-5fc98097bfbb9d7c.rlib   libdoc_comment-d8fc5586c1f80845.rmeta
1
> target/debug/deps/libd
```

**Comment by lightclient** [comment]
I’m AFK until Monday, but will try then.

**Comment by lightclient** [comment]
@gwenn thanks for sharing that code. I can confirm that #392 is solves this issue in the rustyline example. I will need to spend some time debugging in `nushell` to better understand why it is still broken there. I will go ahead and close this issue for now.

**Comment by gwenn** [comment]
@lightclient I will also try to investigate with `nushell` if I have some spare time and keep you posted.
