### ISSUE TITLE
history left in broken state

### ISSUE THREAD

**Issue by avsej** [kkawakam/rustyline#400]
https://github.com/nushell/nushell/issues/1977

The library always overwrites the history which does not have practical value. Instead it must only append new lines to the existing file.

**Comment by gwenn** [comment]
https://github.com/kkawakam/rustyline/blob/master/src/history.rs#L125
```rust
    // TODO append_history
```
not supported.

**Comment by gwenn** [comment]
Could you please give a try to PR #419 ?

**Comment by gwenn** [comment]
Version 7.0.0 released
