### ISSUE TITLE
Windows and paths with n in them

### ISSUE THREAD

**Issue by fdncred** [kkawakam/rustyline#409]
Windows 10 2004.

Somewhere along the way, paths are getting stored in the history.txt file wrong. For instance, I work on a project called NuShell. Here's an entry from my history.txt file.
`
cd source\\repos\\forks\\\nushell\\
`
Notice that there are one too many back slashes in the entry. The ramification of this is that when I try to recall it, this happens.
![image](https://user-images.githubusercontent.com/343840/86010341-e3918880-b9e0-11ea-8adc-22c6a921ddbf.png)

Any ideas what is going on here? I'm assuming it has something to do with either the history loading or saving or both.

**Comment by bjorn3** [comment]
This is expected. Both backslash and newline are escaped when writing the history file. They are unescaped when loading it again. The history file has a single history entry per line, so newlines must be escaped as `\n`. This in turn requires `\` to be escaped as `\\` to prevent ambiguity when you write `\n` and not a newline.

https://github.com/kkawakam/rustyline/blob/380995919c0dc0565aa71b352400ed0e5f4a15d0/src/history.rs#L143-L144

https://github.com/kkawakam/rustyline/blob/380995919c0dc0565aa71b352400ed0e5f4a15d0/src/history.rs#L173

**Comment by fdncred** [comment]
> This is expected. 

So, it's expected to not work properly with any path that has a folder that begins with `n`?

What about checking for `\n` at the end of a string instead of in the middle. Would that work?

**Comment by bjorn3** [comment]
> Notice that there are one too many back slashes in the entry.

I didn't notice this part when I responded. This is not expected. I think the problem here is that `\n` got turned into `\\n` when written to the history file. So far so good, but when it got read again, the `\n` part first got turned into a newline to form `\<LF>`, this is not correct. When this is written again it forms `\\\n`. The solution would be to replace the two `replace` calls with a single pass that replaces `"\\n"` with `"\n"` and `"\\\\"` with `"\\"` at the same time.

**Comment by gwenn** [comment]
Thanks you for both report and analysis.

**Comment by gwenn** [comment]
See #412
There may be a more idiomatic way to lazily / conditionally make a partial copy (https://github.com/kkawakam/rustyline/pull/412/files#diff-fe6f8eb00378a6fd24f0b8c7f0cb9cebR194) ?

**Comment by gwenn** [comment]
6.3.0 released
