### ISSUE TITLE
Support partial completions

### ISSUE THREAD

**Issue by ryanpcmcquen** [kkawakam/rustyline#413]
Would it be possible to get partial completions, like `fish` provides with the <kbd>Alt</kbd> and arrow combos?

Example:
![partial_completion](https://user-images.githubusercontent.com/772937/86825136-dfe6ad00-c043-11ea-9751-93b12d80ffb0.gif)

I also logged the request here as well:
https://github.com/nushell/nushell/issues/2135

**Comment by gwenn** [comment]
Version 8.1.0 released
