### ISSUE TITLE
With `EditMode::Vi`, insert mode should not have `keyseq_timeout` applied when receiving `KeyPress::Esc`

### ISSUE THREAD

**Issue by bobbygebert** [kkawakam/rustyline#416]
When in insert mode, you have to wait for 500ms (or whatever timeout was given in the editor config).  I would expect hitting the escape key to return to command mode immediately.

**Comment by gwenn** [comment]
See https://github.com/kkawakam/rustyline/issues/371
> In vi mode, when you read an ESC from stdin, you don't know if it is a single escape or an escape sequence

**Comment by homburg** [comment]
@gwenn Maybe we could change the default value for vi mode timeout? There is not delay in zsh/bash vi mode.

**Comment by gwenn** [comment]
Are you sure ?
https://tiswww.case.edu/php/chet/readline/readline.html
> int rl_set_keyboard_input_timeout (int u)

https://stackoverflow.com/questions/44890662/disable-timeout-on-esc-key
> ttimeoutlen timeoutlen

https://python-prompt-toolkit.readthedocs.io/en/master/pages/advanced_topics/key_bindings.html?highlight=timeoutlen#timeouts

**Comment by homburg** [comment]
No, you are absolutely right.

Tested some different delays for switching from insert mode to command mode with escape:

| environment | shell | delay | reference |
|---|---|---|---|
| macOS | bash | ~0ms | ? |
| ubuntu (docker) | bash | 500ms | ... |
| macOS | zsh | 400ms | https://github.com/zsh-users/zsh/blob/b74635aa741d7e2d8d81f601f0192e79037aa991/Src/params.c#L823 |
| alpine (docker) | ash | ~100ms | ? |
| * | fish shell | 30ms | https://github.com/fish-shell/fish-shell/issues/6590 :-) |

An important distinction is that bash seems to recognize command movement keys immediately after escape, eg:

1. `<insert mode>`
2. input: `Esc`, `h`
3. (without delay) `<command mode>`, caret one step left

Not sure how that's implemented

**Comment by gwenn** [comment]
Currently, `rustyline` reads only one byte at a time.
If a library reads several bytes at once, there is no need to wait if there is another byte after an ESC.

**Comment by bobbygebert** [comment]
Yeah @homburg, the fact that movement keys aren't respected after escape is what surprised me. Maybe that is the solution. We could add key sequence rules for those combinations pretty easily, right?

**Comment by homburg** [comment]
@bobbygebert Sounds like a good strategy, what do you think @gwenn ?

For reference, I think this is relevant bash readline logic: https://git.savannah.gnu.org/cgit/readline.git/tree/readline.c#n901 but I'm not familiar enough with the code to understand it.

**Comment by gwenn** [comment]
I am not sure to understand:
> the fact that movement keys aren't recognized after escape is what surprised me.
Does it mean that movement keys are not recognized when timeout is too low ?
Or does it mean that movement keys are not recognized even when timeout is high ?

**Comment by homburg** [comment]
@gwenn it means that bash recognizes the movement keys, eg. `j` as `<command-mode>` keys _during_ the timeout, ie. `esc, j` -> instant `<command mode>`

**Comment by homburg** [comment]
@gwenn I did a quick proff-of-concept, that seems to match the behavior: https://github.com/kkawakam/rustyline/pull/426

**Comment by gwenn** [comment]
@homburg Ok, I understand now. We don't expect Meta-X in Vi mode only escape sequence. So Meta-X means Esc (exit insert mode) and do command associated to X. Looks good to me. We should be able to refactor/split `vi_command` method and call the bottom part from your patched block in `vi_insert`. 
Thanks.

**Comment by gwenn** [comment]
6.3.0 released
