### ISSUE TITLE
Prompt for numeric entry only

### ISSUE THREAD

**Issue by jamesmcm** [kkawakam/rustyline#436]
Hi,

I'd like to create a prompt which only accepts numeric entries, i.e. any non-numeric character key-presses do not register (or optionally, trigger the bell).

Is there any way to specify which input characters are accepted? (one could imagine the same idea would be useful for alpha-numeric only, etc.)

**Comment by gwenn** [comment]
Currently, we can't easily.
You can only reject user input with a [Validator](https://docs.rs/rustyline/*/rustyline/validate/trait.Validator.html).
An ugly and partial solution would be to [rebind](https://docs.rs/rustyline/6.2.0/rustyline/struct.Editor.html#method.bind_sequence) all ascii characters to `Noop`.

**Comment by gwenn** [comment]
Fixed in version 8.0.0
See https://github.com/kkawakam/rustyline/blob/master/examples/numeric_input.rs
