### ISSUE TITLE
Multi-line prompt appears to function incorrectly

### ISSUE THREAD

**Issue by sector-f** [kkawakam/rustyline#44]
I'm attempting to create a multi-line prompt by using a newline character in the argument to `Editor::readline`, e.g. `readline("foo\n> ")`

I expected this to produce
````
foo
>
````
but it is instead producing
````
foo
   >
````
Is this a problem with rustyline, or am I doing something incorrectly?

**Comment by kkawakam** [comment]
Fixed in master
