### ISSUE TITLE
Save lines in history file with a Unix timestamp

### ISSUE THREAD

**Issue by avinashkanaujiya** [kkawakam/rustyline#442]
Just What I said above...

**Comment by gwenn** [comment]
Maybe we should introduce a Trait like [termwiz](https://docs.rs/termwiz/0.9.0/termwiz/lineedit/trait.History.html) and provide only a default implementation ?

**Comment by walles** [comment]
Should this ticket be marked as a duplicate of #127?

With custom history load / save functionality people could add whatever they wanted, and this ticket would be up to the crate users to deal with.

**Comment by gwenn** [comment]
2 years later => #604
Feedback is welcome.

**Comment by gwenn** [comment]
Version 11.0.0 released.
