### ISSUE TITLE
readline_direct and readline_raw don't handle EINTR

### ISSUE THREAD

**Issue by Allen-Webb** [kkawakam/rustyline#454]
The "readline_direct" and "readline_raw" functions error out if EINTR is received. This functions should arguably retry the read operations if they receive EINTR. This leads to Editor::<ReadLineHelper>::readline(...) failing. I could call that again, but it is far enough from the low level read call that it doesn't make sense especially since it prints a prompt.

**Comment by bjorn3** [comment]
Not handling `EINTR` makes sense for for example a shell that doesn't make `SIGINT` exit the program. Every shell I know does actually print a new prompt. In addition repl's like python and node and debuggers like gdb and lldb actually print an extra message when you use ctrl-c.

```
$ python
>>> 
KeyboardInterrupt
>>> 
```

```
$ node
> 
(To exit, press ^C again or type .exit)
>
```

```
$ gdb
(gdb) Quit
(gdb) 
```

```
$ lldb
(lldb) ^C
(lldb) 
```

**Comment by gwenn** [comment]
Are you receiving an `error::ReadlineError::Eof` or an `error:: ReadlineError::Io(...Interrupted...)` ?
* For `readline_direct`, we should be able to transform `error:: ReadlineError::Io(...Interrupted...)` into `error::ReadlineError::Eof`.
* For `readline_raw`, we should not send `error:: ReadlineError::Io(...Interrupted...)` but `error::ReadlineError::Eof` because:
   - on unix, `BRKINT` is disabled but maybe `EINTR` can still happen (for example, when calling `poll`) ?
   - on windows, I am not sure (maybe `ENABLE_PROCESSED_INPUT`) ?

Could you please provide your OS and a backtrace ?

**Comment by Allen-Webb** [comment]
I saw this happen on Chrome OS (Linux). In the past I have been able to reproduce EINTR issues using SIGSTOP and SIGCONT, but that didn't reproduce the issue for me. I wonder if I was wrong and the EINTR is actually happening if a stop signal is received while writing out the prompt instead of the read calls.

This is the error message I am seeing:
2020-09-21T17:59:08.371949-04:00 ERR crosh[5246]:  [src/main.rs:291] ReadLine error: EINTR: Interrupted system call
This is the line of code that prints the error:
https://chromium.googlesource.com/chromiumos/platform2/+/470dadbe1936e0a2aae58a14a7a81bb46e3885ef/crosh/src/main.rs#299
I catch both ReadlineError::Eof and ReadlineError::Interrupted


Here is the bug we have tracking this issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=1130808

**Comment by gwenn** [comment]
I will try to reproduce on a VM.

**Comment by Allen-Webb** [comment]
This isn't critical for us as I am trying a workaround that involves catching the error and handling it the same as ReadlineError::Interrupted

@@ -292,6 +292,9 @@
             Err(ReadlineError::Interrupted) => {
                 buffer.clear();
             }
+            Err(ReadlineError::Io(ioe)) if ioe.kind() == std::io::ErrorKind::Interrupted => {
+                buffer.clear();
+            }
             Err(ReadlineError::Eof) => {
                 break;
             }

https://chromium-review.googlesource.com/c/chromiumos/platform2/+/2473120/3/crosh/src/main.rs

**Comment by gwenn** [comment]
See #458 (only `readline_raw` has been fixed).
See also #448.

**Comment by gwenn** [comment]
Version 7.0.0 released
