### ISSUE TITLE
Performance: check that no lock is used when refreshing screen

### ISSUE THREAD

**Issue by gwenn** [kkawakam/rustyline#462]
https://nnethercote.github.io/perf-book/io.html
> Rust’s print! and println! macros lock stdout on every call.

[write_all](https://doc.rust-lang.org/src/std/io/stdio.rs.html#599-601) too !
What about linefeed / liner / termwiz ?
I guess we can use the file descriptor / handle directly !

**Comment by bjorn3** [comment]
You can use `std::io::stdout().lock()` once and then perform multiple write calls on the resulting lock.
