### ISSUE TITLE
`dirs` is no longer maintained

### ISSUE THREAD

**Issue by Razican** [kkawakam/rustyline#467]
Hello,
The `dirs` crate is no longer maintained, and the projeect migrated to `dirs-next` in #388. There is a comment there that seems to imply it's active, but as you can see in [its repository](https://github.com/dirs-dev/dirs-rs), it's been archived. Also, the newest versions of `dirs-next` are newer to those in `dirs`, so this part of #456 should probably be reverted.

Note that there is a RUSTSEC advisory about it: https://rustsec.org/advisories/RUSTSEC-2020-0053.html

**Comment by gwenn** [comment]
See https://github.com/kkawakam/rustyline/pull/388#issuecomment-657522832
>

**Comment by gwenn** [comment]
7.1.0 released.
