### ISSUE TITLE
German keymap does not work correctly on Windows 10

### ISSUE THREAD

**Issue by tofpie** [kkawakam/rustyline#475]
In the German keymap some characters (like |) are inserted by pressing the modifier key `Alt Gr`. This does not work in rustyline.

It seems that `Alt Gr` (which is `Alt` + `Ctrl`) is interpreted as `Ctrl` on Windows:

https://github.com/kkawakam/rustyline/blob/4a87a1944ee73bcad760b44699e145ee64657a83/src/tty/windows.rs#L140-L152

**Comment by gwenn** [comment]
7.1.0 released.
