### ISSUE TITLE
Prompt prints from beginning of line

### ISSUE THREAD

**Issue by dancojocaru2000** [kkawakam/rustyline#479]
When I call `Editor::readline`, the prompt is written at the beginning of the line. If there is some output already on the current line, that output is overridden.

How can this be avoided?

**Comment by gwenn** [comment]
https://docs.rs/rustyline/7.1.0/rustyline/config/struct.Config.html#method.check_cursor_position
This setting has been deactivated by default recently: https://github.com/kkawakam/rustyline/issues/445

**Comment by dancojocaru2000** [comment]
Ah, thanks! I'm on the go, will try later. 

As I workaround, I used the crossterm crate to check the cursor position and manually print a new line, but I'm glad that I can avoid adding an extra crate just for that.

Will check if it works later, but thanks!
