### ISSUE TITLE
readline() can return multiple lines

### ISSUE THREAD

**Issue by rwestphal** [kkawakam/rustyline#480]
I've just found out that Editor::readline() can return multiple lines if one pastes a multi-line string from the clipboard into the terminal. Example:
```
root@debian:/mnt/renato/git/rust/rustyline# cargo run --example diy_hints
[snip]
This is a DIY hint hack of rustyline
> abc
def
ghi

input: abc
def
ghi

> 
```

Is this the expected behavior? If yes, is there a way I can change Editor::readline() to break the input into multiple lines (so that they can be parsed separately)?

**Comment by gwenn** [comment]
You can either:
* [disable](https://github.com/kkawakam/rustyline/issues/202) bracketed paste mode. And you will received one line at a time.
* or split input yourself on `\n` (as far as I know, there will be distinction between a [continuation](https://docs.rs/rustyline/7.1.0/rustyline/enum.Cmd.html#variant.AcceptOrInsertLine) line and pasted text which contains newline(s)).

**Comment by rwestphal** [comment]
> * [disable](https://github.com/kkawakam/rustyline/issues/202) bracketed paste mode. And you will receive one line at a time. You should be aware that `rustyline` is slow when pasted text is big.

@gwenn thanks for the quick response! That did the trick for me.

For future reference, here's how to disable the bracketed paste mode after the latest API changes:
```
rl.bind_sequence(KeyEvent(KeyCode::BracketedPasteStart, Modifiers::NONE), Cmd::Noop);
```

Closing...
