### ISSUE TITLE
Add composite commands

### ISSUE THREAD

**Issue by sigmaSd** [kkawakam/rustyline#487]
Hello,

What do you think about adding this command:

```rust
enum Cmd {
Composite(Vec<Cmd>),
}
```

I needed this for the vi `o/O` commands, and I imagine other complex commands will need it. 

Here is an example https://github.com/kkawakam/rustyline/compare/master...sigmaSd:clear_buffer?expand=1

**Comment by gwenn** [comment]
See #418, #306, #466, #342

**Comment by sigmaSd** [comment]
Closing then since the exact same issue was filed https://github.com/kkawakam/rustyline/issues/306
