### ISSUE TITLE
Insert tab when the cursor is ontop a whitespace character

### ISSUE THREAD

**Issue by sigmaSd** [kkawakam/rustyline#488]
Currently `Complete command` disables tab completely.

Personally I prefer for it to insert an actual tab when the cursor is on top a white-space character (since that very probably means that the user is not looking for completion).

Here is an example https://github.com/kkawakam/rustyline/compare/master...sigmaSd:insert_tab?expand=1

**Comment by gwenn** [comment]
See #269 and #293

**Comment by sigmaSd** [comment]
#293 should allow this indeed, thanks I'll just close this, no need to clutter the issue tracker.

**Comment by gwenn** [comment]
Fixed in version 8.0.0
