### ISSUE TITLE
Case-insensitive history search

### ISSUE THREAD

**Issue by tailhook** [kkawakam/rustyline#490]
I'd like to have case-insensitive search of the history. And it looks like history search is hardcoded now. How should I approach the problem:
1. Allow customizing history search?
2. Add `case_insensitive` (or similar) config parameter?
2. Make case insensitive default (if that makes more sense)?

**Comment by gwenn** [comment]
If possible we should behave like `readline` which seems to be [case-sensitive](https://tiswww.case.edu/php/chet/readline/readline.html#SEC10).
So (2) seems good to me.
I will try to see how other libraries behave by default.

**Comment by gwenn** [comment]
It seems that we need the `regex` crate (https://github.com/rust-lang/rfcs/issues/1988).
And we cannot use `std::str::pattern` (yet): https://docs.rs/regex/1.1.0/regex/struct.Regex.html#using-the-stdstrpattern-methods-with-regex

**Comment by gwenn** [comment]
See #546 but you may not like the cargo feature...

**Comment by tailhook** [comment]
I'm fine with it being cargo feature. I think that case-insensitive here is what users would expect, and it's fine that it's a feature because of having an extra dependency.

**Comment by gwenn** [comment]
Version 9.0.0 released.
