### ISSUE TITLE
Can't add history line with preceding spaces

### ISSUE THREAD

**Issue by sourtin** [kkawakam/rustyline#50]
Entries with whitespace at the beginning of the string are excluded from the history object by history.rs:34. Perhaps the line could be replaced with `if line.trim().is_empty() {` so that only lines entirely made of whitespace are excluded?

**Comment by sourtin** [comment]
In fact perhaps it should be up to the user whether or not to add lines of pure whitespace? I can see some use in it if e.g. you're typing multiline expressions, or making a whitespace interpreter. In which case maybe the entire block should be removed or made an option.

**Comment by gwenn** [comment]
It's my fault.
I reproduced the `ignorespace` behaviour from [bash](http://man7.org/linux/man-pages/man1/bash.1.html#HISTORY).
I will try to introduce settings.

**Comment by sourtin** [comment]
Thanks a lot!
