### ISSUE TITLE
overwriting output with the prompt

### ISSUE THREAD

**Issue by fdncred** [kkawakam/rustyline#503]
it appears that `nushell` is working with the latest `rustyline` almost. when we do things like `echo 1` it spits out `1` and then `rustyline` immediately overwrites it with the prompt. any ideas whether this is problem is withing `rustyline` or `nushell`? Is this a known issue?

![rusty](https://user-images.githubusercontent.com/343840/110866749-3f5c2300-828b-11eb-9580-473472a6668c.gif)

**Comment by bjorn3** [comment]
I think the problem is that nushell doesn't print a newline afterwards. It could be handled better by rustyline though. Zsh uses a trick to end the line with a % and go to the next line if there is no trailing newline. It was something like printing a %, then termwidth-2 spaces and then `\r` to go back to the start of the line. If the line was not empty, it will overflow to the next line, leaving the % behind. If not, the % will be overwrittem by the prompt.

**Comment by jonathandturner** [comment]
@bjorn3 - this wasn't an issue with previous versions of rustyline. It seems that more recent versions have this effect.

**Comment by fdncred** [comment]
@gwenn  any ideas? I have validated that nushell is adding a `\n`, as it did before with prior versions of rustlyine, but with the latest version, on single string outputs rustyline is eating it.
```rust
        let mut initial_command = Some(String::new());
        let mut readline = Err(ReadlineError::Eof);
        while let Some(ref cmd) = initial_command {
            readline = rl.readline_with_initial(&prompt, (&cmd, ""));
            initial_command = None;
        }

        if let Ok(line) = &readline {
            line_start = session_text.len();
            session_text.push_str(line);
            session_text.push('\n');
        }
```

i've also validate with this code that there is 1 `\n` in the output for multiline output and single string output.

```rust
        let crs = session_text[line_start..].matches('\n').count();
        print!("{}", crs);
```

**Comment by bjorn3** [comment]
Isn't that code for the input from readline rather than the output of the `echo` command?

**Comment by jonathandturner** [comment]
@bjorn3 - We're asking if there's a way to get the previous rustyline behavior in the recent (8.0) rustyline.

**Comment by ahkrr** [comment]
I looked into this. 
The problem that `nushell` is facing probably stems from the introduction of this
``` rust
    /// Check if cursor position is at leftmost before displaying prompt.
    ///
    /// By default, we don't check.
    pub fn check_cursor_position(&self) -> bool {
        self.check_cursor_position
    }
```
if I haven't messed to much with the files during my investigation and created some intermediate state
`nushell` should be able to get their old behaviour back by 
``` rust 
// crates/nu-cli/src/line_editor.rs +46
    let config = Config::builder()
        .check_cursor_position(true) // <--- introducing this line
        .color_mode(ColorMode::Forced)
        .build();
```
introducing this line into their setup of the `rustyline config` and then migrate to `rustyline_8`

**Comment by gwenn** [comment]
Sorry, it should have been considered as a breaking change:
https://github.com/kkawakam/rustyline/releases/tag/v7.0.0
https://github.com/kkawakam/rustyline/pull/448#issuecomment-703218098
https://github.com/kkawakam/rustyline/issues/445

**Comment by fdncred** [comment]
Thanks for the info.
