### ISSUE TITLE
the trait `std::marker::Send` is not implemented for `Rc<RefCell<(dyn line_buffer::ChangeListener + 'static)>>`

### ISSUE THREAD

**Issue by kdheepak** [kkawakam/rustyline#508]
Hi,

I'm trying to use `rustyline`'s `LineBuffer` struct in one of my TUI applications and it has been working out great! However, I'm currently trying to write a `async` version of my application and I'm running into the following error:

```
error: future cannot be sent between threads safely
  --> src/main.rs:78:21
   |
78 |                     task::spawn(async move {
   |                     ^^^^^^^^^^^ future created by async block is not `Send`
   |
  ::: /Users/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/spawn.rs:28:29
   |
28 |     F: Future<Output = T> + Send + 'static,
   |                             ---- required by this bound in `async_std::task::spawn`
   |
   = help: within `TaskwarriorTuiApp`, the trait `std::marker::Send` is not implemented for `Rc<RefCell<(dyn line_buffer::ChangeListener + 'static)>>`
note: captured value is not `Send`
  --> src/main.rs:79:25
   |
79 |                         app.lock().await.render(&mut *terminal.lock().await).await
   |                         ^^^ has type `Arc<async_std::sync::Mutex<TaskwarriorTuiApp>>` which is not `Send`
```

> the trait `std::marker::Send` is not implemented for `Rc<RefCell<(dyn line_buffer::ChangeListener + 'static)>>`

Is this something that can be added to `rustyline`?

**Comment by gwenn** [comment]
Replace `Rc` by `Arc` (and, maybe, only if an optional feature is activated) ?

**Comment by gwenn** [comment]
Indeed !
So 42b1607ae3176a821925199e58473a2175c6da64 doesn't really work...
In your PR, could you please add an [assert_send](https://github.com/kkawakam/rustyline/blob/master/src/tty/unix.rs#L1172-L1176).
Thanks.

**Comment by kdheepak** [comment]
I added a `assert_send` and `assert_sync`. Let me know what you think.

**Comment by gwenn** [comment]
Version 11.0.0 released.
