### ISSUE TITLE
Tab completion doesn't work on tab

### ISSUE THREAD

**Issue by zohnannor** [kkawakam/rustyline#515]
Completion is not triggered when TAB is pressed, only on the right arrow.
Is this a windows issue? Tested in cmd.exe, pwsh.exe, wsl in VSCode integrated terminal.

**Comment by gwenn** [comment]
Cannot reproduce !
```sh
> cargo run --example example
    Finished dev [unoptimized + debuginfo] target(s) in 2.70s
     Running `target\debug\examples\example.exe`
1> tar
```
Typing TAB gives:
```
1> target/
```

**Comment by zohnannor** [comment]
I realized that I did not implemented `Completer` properly...
