### ISSUE TITLE
How to make CTRL-V paste on windows (cmd.exe, powershell)

### ISSUE THREAD

**Issue by marcbowes** [kkawakam/rustyline#519]
When using rustyline on Linux or OSX, system copy-paste works just fine. However, on Windows that's not the case.

Here's a scenario that doesn't work as expected:

1. Open notepad and type some text. Select it, use CTRL-C to put it on the clipboard.
2. Open cmd.exe and press CTRL-V. The text should paste.
3. Open a rustyline application (e.g. the default example will do). Press CTRL-V. The next *will not paste*.
4. Use rightclick. The text will paste.

The same thing is true when using Powershell. When using Windows Terminal, CTRL-V works as expected.

I looked through the available keybinds/commands and I don't see a "paste from system clipboard" anywhere. Should this work by default, or is there something I need to enable?

**Comment by gwenn** [comment]
I only have access to a Windows machine at work.
To check:
- how does [linefeed](https://github.com/murarth/linefeed) / [termwiz](https://github.com/wez/wezterm/tree/main/termwiz) / [replxx](https://github.com/AmokHuginnsson/replxx) behave ?
- For rustyline, by default, CTRL-V does nothing on Windows and there is no command to "paste from system clipboard" so you cannot use [bind_sequence](https://docs.rs/rustyline/8.0.0/rustyline/struct.Editor.html#method.bind_sequence).
- Maybe you should try to tweak Command / Powershell settings.

**Comment by marcbowes** [comment]
Well, that's pretty clear! Thanks.

I know literally nothing about the windows API. If you can point me at some method names, I can try implement it.

**Comment by marcbowes** [comment]
https://github.com/marcbowes/rustyline/commit/b0e2669acacf9c259f0f73bc1d9d8f271f8a07c2

I'll test that out later on my Windows machine. If it works, I'll wire up a paste command.

**Comment by marcbowes** [comment]
See the above PR for a fix. Not sure if I did it right. Also had to revert the fd-lock change to get things compiling.

**Comment by gwenn** [comment]
Version 8.1.0 released

**Comment by marcbowes** [comment]
Thank you!
