### ISSUE TITLE
How to change path for FilenameCompleter?

### ISSUE THREAD

**Issue by doggo-rules** [kkawakam/rustyline#528]
I'm making a shell and I keep the current directory in a string. The issue is, FilenameCompleter completes files from the starting directory (where the shell was started) and not that string. Is there any way I can pass the string to FilenameCompleter or something to complete files in that path?

**Comment by gwenn** [comment]
https://doc.rust-lang.org/std/env/fn.set_current_dir.html ?

**Comment by doggo-rules** [comment]
oh alright, thanks
