### ISSUE TITLE
how to apply key bindings

### ISSUE THREAD

**Issue by fdncred** [kkawakam/rustyline#543]
What's the secret sauce to get either of these to work in the `custom_key_bindings` example in Windows Terminal? Am I specifying the handler wrong?

```rust
    // rl.bind_sequence(
    //     KeyEvent {
    //         0: KeyCode::Char('H'),
    //         1: Modifiers::CTRL,
    //     },
    //     Cmd::Kill(Movement::BackwardChar(1)),
    // );

    rl.bind_sequence(KeyEvent::ctrl('h'), Cmd::Kill(Movement::BackwardChar(1)));
```

**Comment by gwenn** [comment]
I am not sure (and I don't have access to a windows desktop right now) but I guess it is because on unix, there is no way to make the distinction between Ctrl-h and Ctrl-H: https://github.com/kkawakam/rustyline/blob/master/src/keys.rs#L93
And we apply the same logic on Windows!

**Comment by fdncred** [comment]
For the record, I've tried it with upper and lower and neither works on Windows. I added some debugging and it appears to be registered properly. It just doesn't trigger when you tyle Ctrl-h or Ctrl-H
```
    Finished dev [unoptimized + debuginfo] target(s) in 1.01s
     Running `C:\CarTar\debug\examples\custom_key_bindings.exe`
Event: [KeySeq([KeyEvent(Tab, NONE)])] Handler: ["conditional"]
Event: [KeySeq([KeyEvent(Char('E'), CTRL)])] Handler: ["conditional"]
Event: [KeySeq([KeyEvent(Char('H'), CTRL)])] Handler: ["Kill(BackwardChar(1))"]
Event: [KeySeq([KeyEvent(Char('X'), CTRL), KeyEvent(Char('E'), CTRL)])] Handler: ["Suspend"]
Event: [KeySeq([KeyEvent(Char('f'), ALT)])] Handler: ["conditional"]
> 
```

**Comment by gwenn** [comment]
You may be able to spot the issue by activating debug traces.
Just add this line:
https://github.com/kkawakam/rustyline/blob/master/examples/example.rs#L82-L84
```rust
fn main() -> rustyline::Result<()> {
    env_logger::init(); // <--
```
And then:
```cmd
set RUST_LOG=rustyline=debug
cargo run --example custom_key_bindings 2> debug.log
```

**Comment by fdncred** [comment]
I did that (without the redirection), and typed `time` in and then hit <kbd>ctrl+h</kbd> 3 times. This is what it showed.
```
t[DEBUG rustyline::tty::windows] key: KeyEvent(Char('i'), NONE)
[DEBUG rustyline::keymap] Emacs command: SelfInsert(1, 'i')
[DEBUG rustyline::undo] Changeset::insert(12, 'i')
i[DEBUG rustyline::tty::windows] key: KeyEvent(Char('m'), NONE)
[DEBUG rustyline::keymap] Emacs command: SelfInsert(1, 'm')
[DEBUG rustyline::undo] Changeset::insert(13, 'm')
m[DEBUG rustyline::tty::windows] key: KeyEvent(Char('e'), NONE)
[DEBUG rustyline::keymap] Emacs command: SelfInsert(1, 'e')
[DEBUG rustyline::undo] Changeset::insert(14, 'e')
e[DEBUG rustyline::tty::windows] key: KeyEvent(Backspace, CTRL)
[DEBUG rustyline::keymap] Emacs command: Unknown
[DEBUG rustyline::tty::windows] key: KeyEvent(Backspace, CTRL)
[DEBUG rustyline::keymap] Emacs command: Unknown
[DEBUG rustyline::tty::windows] key: KeyEvent(Backspace, CTRL)
[DEBUG rustyline::keymap] Emacs command: Unknown
```

**Comment by gwenn** [comment]
`KeyEvent(Backspace, CTRL)` is not expected !
So,
1. We must fix this line:
https://github.com/kkawakam/rustyline/blob/master/src/keys.rs#L36
```rust
            '\x08' => E(K::Backspace, mods ^ CTRL),
```
or remove the `CTRL` bit when `c.is_control()` here:
https://github.com/kkawakam/rustyline/blob/master/src/tty/windows.rs#L204

2. You must use `Backspace` in your custom bindings.

**Comment by gwenn** [comment]
Or to keep the distinction between the backspace key and ctrl-h, we need to fix this:
https://github.com/kkawakam/rustyline/blob/master/src/tty/windows.rs#L180
```rust
                        winuser::VK_BACK => K::Backspace,
```
And skip https://github.com/kkawakam/rustyline/blob/master/src/keys.rs#L36 on windows.
I will be able to test on windows tomorrow...

**Comment by gwenn** [comment]
https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1384

**Comment by fdncred** [comment]
I changed this:


```rust
           '\x08' => E(K::Backspace, mods),           // '\b'
```

to this:
```rust
            '\x08' => E(K::Char('H'), mods | M::CTRL), // '\b'
```

and it seems to work fine on windows now.

**Comment by gwenn** [comment]
Thanks.
I will test this branch tomorrow:
https://github.com/gwenn/rustyline/blob/windows_keys/src/keys.rs#L38-L39

**Comment by gwenn** [comment]
See #547

**Comment by fdncred** [comment]
Looks good. Ship it! :)

**Comment by gwenn** [comment]
Version 9.0.0 released.
