### ISSUE TITLE
Run hinter again after hint is inserted with right arrow

### ISSUE THREAD

**Issue by pacak** [kkawakam/rustyline#555]
At the moment text inserted by the right arrow won't trigger for an update for the next hint while text inserted by completion would. 

Consider an example for command line interface for file deletion with the only command being `rm [filename]`.
Suppose user types `r`, I want to display a hint either `m` or `m [filename]` but immediately after completion it should be `rm` followed by a hint `[filename]`.

Also a question: What's the difference between completion via hint and completion via complete, and which one should be used in which situations?

**Comment by gwenn** [comment]
We need to check why [refresh_line_with_msg](https://github.com/kkawakam/rustyline/blob/master/src/lib.rs#L268) is used (instead of `refresh_line`).

**Comment by gwenn** [comment]
Could you please give #556 a try ?
https://github.com/kkawakam/rustyline/blob/master/examples/diy_hints.rs#L80
```sh
% cargo run --example diy_hints
```

**Comment by pacak** [comment]
Yep, this works as expected with my code without any changes. Thank you.

**Comment by gwenn** [comment]
Version 9.0.0 released.
