### ISSUE TITLE
History file can become corrupted in certain circumstances

### ISSUE THREAD

**Issue by lily-mara** [kkawakam/rustyline#559]
This one took quite a bit of wrangling to reproduce and I'm still not confident that it's exactly hitting the issue. There are two things going on here working together, and I can break them into multiple issues if that's desired.

1. If multiple rustyline editors are writing to the same file in parallel, it may write duplicate lines, even when running with duplicate lines turned off. This would be okay if not for the second issue
2. If a history file contains multiple duplicate lines when rustyline opens it in non-duplicate mode, rustyline will strip characters out of the beginning of lines.

These two things combine to mean that parallel writes on a history file (such as when it's used from multiple shell processes) can cause the file to become corrupted.

Code examples and the following explanation are also available in this repo https://github.com/lily-mara/rustyline-test

## When there are duplicate lines

```
use std::{
    fs::File,
    io::{Read, Write},
};

use rustyline::Editor;

const PATH: &str = "history/init.txt";

fn main() {
    let mut f = File::create(PATH).unwrap();

    f.write_all(b"#V2\nA --- long line\nA --- long line\n")
        .unwrap();

    f.flush().unwrap();
    drop(f);

    let mut e = Editor::<()>::new();

    e.add_history_entry("B");
    e.append_history(PATH).unwrap();

    drop(e);

    let mut f = File::open(PATH).unwrap();
    let mut s = String::new();
    f.read_to_string(&mut s).unwrap();

    println!("{}", s);
}
```

This test shows that when there are multiple duplicate lines in a history file
before rustyline opens it, it will truncate lines after editing the file.

The test writes this data to the history file with raw IO:

```
#V2
A --- long line
A --- long line

```

Next it creates a rustyline `Editor` and tells it to add the line `"B"` to the
history file. Finally it prints the contents of the history file so you can see
what it outputs.

Actual output:

```
#V2
A --- long line
B
--- long line
```

Expected output:

```
#V2
A --- long line
A --- long line
B
```

or

```
#V2
A --- long line
B
```

This should be fine, because rustyline should not write duplicate lines to the
history file. Unfortunately I have found that parallel writes can cause this to
happen.

## Parallel writes

```
use std::{
    fs::{remove_file, File},
    io::Read,
};

use rustyline::Editor;

const PATH: &str = "history/parallel.txt";

fn main() {
    let _ = remove_file(PATH);

    let t = std::thread::spawn(|| {
        run();
    });

    run();

    t.join().unwrap();

    println!("After parallel writes");
    print_contents();

    run();

    println!("After final writes");
    print_contents();
}

fn print_contents() {
    let mut f = File::open(PATH).unwrap();
    let mut s = String::new();

    f.read_to_string(&mut s).unwrap();
    println!("{}", s);
}

fn run() {
    let mut e = Editor::<()>::new();
    dump_stuff(&mut e);
    write(&mut e, "ls");
    dump_stuff(&mut e);
}

fn dump_stuff(e: &mut Editor<()>) {
    for i in 0..2 {
        write(e, &format!(".......... {}", i));
    }
}

fn write(e: &mut Editor<()>, data: &str) {
    e.add_history_entry(data);
    e.append_history(PATH).unwrap();
}
```

This example shows that parallel writes can cause rustyline to duplicate lines,
which then leads to line truncation. This example uses no raw IO, it only uses
the rustyline library to write to the history file. It does _read_ from the file
using the rust stdlib but this is for convenience only and removing those reads
do not impact rustyline's behavior.

We have a function `run` which does the following:

- write some long lines to the history file
- write `ls` to the history file
- write some more long lines to the history file

We first run this function in parallel. Once on the main thread and once on a
background thread. At this point there should be some duplicate lines in the
file and we print out the contents of the file.

After this, we start a fresh rustyline editor, go through `run` again, and we
see the truncation bug show up.

Actual output (slightly random, depends on threading):

```
After parallel writes
#V2
.......... 0
.......... 1
.......... 1
ls
ls
.......... 0
.......... 0
.......... 1
.......... 1

After final writes
#V2
.......... 0
.......... 1
ls
.......... 0
.......... 1
.......... 0
 0
.......... 1
.......... 1
.......... 1
ls
.......... 0
.......... 1
```

Notice the line containing only ` 0`. This line was truncated. Notice that the
third `ls` does not show up.

Expected output (also slight randomization possible):

```
After parallel writes
#V2
.......... 0
.......... 0
.......... 1
.......... 1
ls
ls
.......... 0
.......... 0
.......... 1
.......... 1

After final writes
#V2
.......... 0
.......... 0
.......... 1
.......... 1
ls
ls
.......... 0
.......... 0
.......... 1
.......... 1
.......... 0
.......... 1
ls
.......... 0
.......... 1
```

**Comment by gwenn** [comment]
Ok, if new history size (without duplicates) < old history size => file is not truncated...

**Comment by gwenn** [comment]
https://stackoverflow.com/questions/58484259/how-can-i-truncate-or-reduce-contents-from-the-end-of-a-file-using-rust

**Comment by gwenn** [comment]
See #560
For concurrent access, we must always use a lock either while reading or writing which is not the case currently...

**Comment by lily-mara** [comment]
Oh very nice, I ran my test cases against that branch and they work perfectly now! Thanks @gwenn!

**Comment by gwenn** [comment]
Version 9.0.0 released.
