### ISSUE TITLE
Colored prompts behave incorrectly on Windows

### ISSUE THREAD

**Issue by acikek** [kkawakam/rustyline#562]
Using the crate `ansi_term`, I added color to a prompt. On my Linux machine, this works as expected. On Windows, however, the behavior is a little strange. For this example, I have an arrow prompt `=>` colored blue. 

- Initially, the prompt is indented.
![image](https://user-images.githubusercontent.com/26909391/131232603-a4baebdc-2607-4684-bdd6-d306294c3815.png)
- If you hit backspace, the entered text shifts to the correct position, but the cursor stays on the right.
![image](https://user-images.githubusercontent.com/26909391/131232619-f4a98be0-f818-42fe-bf27-998e3c610d9d.png)
- From here, you can type the prompt again from the cursor positon...
![image](https://user-images.githubusercontent.com/26909391/131232639-2de9ede9-f7b9-476a-a553-7da8853c43af.png)
- And the characters get pushed back again on backspace.
![image](https://user-images.githubusercontent.com/26909391/131232654-0a565147-5fc7-4590-89d7-f30c97b24cb6.png)

I'm not sure why this is happening, or if this is an issue with rustyline or just Windows itself (this also happens on PowerShell). Any ideas?

**Comment by gwenn** [comment]
Do you use [highlight_prompt](https://docs.rs/rustyline/9.0.0/rustyline/highlight/trait.Highlighter.html#method.highlight_prompt) or use only [readline](https://docs.rs/rustyline/9.0.0/rustyline/struct.Editor.html#method.readline) ?
You should use `highlight_prompt`.
See https://github.com/kkawakam/rustyline/pull/215 for explanations.

**Comment by acikek** [comment]
Did not see that, but very cool nonetheless. I think it'd be nice if it was added to the readme, that would make it a lot clearer.

**Comment by gwenn** [comment]
Version 18.0.0 released with:
https://docs.rs/rustyline/latest/rustyline/trait.Prompt.html
