### ISSUE TITLE
Update 9.1.0 increases MSRV to Rust 1.56.

### ISSUE THREAD

**Issue by link2xt** [kkawakam/rustyline#581]
This update introduced `edition = "2021"` in `Cargo.toml`, which is only supported since Rust 1.56.

We are trying to support MSRV 1.51.0, so can't update to the new version of rustyline because of 2021 edition dependency.

**Comment by gwenn** [comment]
Version 9.1.1 released.

**Comment by link2xt** [comment]
Thanks!
