### ISSUE TITLE
Bracketed paste on Windows?

### ISSUE THREAD

**Issue by schungx** [kkawakam/rustyline#594]
Microsoft Terminal now supports bracketed paste.

Can `enable_bracketed_paste` support be added to Windows targets as well?  Right now, support is only for Unix environments.

**Comment by gwenn** [comment]
1. How do we check / know if `bracketed paste` is supported ?
2. What happens if we try to activate `bracketed paste` on unsupported console / terminal ?

**Comment by schungx** [comment]
> 1. How do we check / know if `bracketed paste` is supported ?

Because Microsoft's release announcement said they added support... and I tried it with the Windows version of vim which worked fine.

>     2. What happens if we try to activate `bracketed paste` on unsupported console / terminal ?

Then pasted text will be prefixed and postfixed by extra escape codes.

**Comment by gwenn** [comment]
I am afraid I will not be able to fix this because I only have limited access (no admin rights, no access to windows store) to a Windows machine at work.

**Comment by schungx** [comment]
> I am afraid I will not be able to fix this because I only have limited access (no admin rights, no access to windows store) to a Windows machine at work.

Anything I can help?  I run a Windows machine.  Or maybe I open up a Windows VM on Azure for you?

**Comment by schungx** [comment]
> Or maybe there is a way to install `microsoft terminal` without admin rights ?

I don't think you can install anything on Windows without admin rights unless it is granted via some explicit policy... 

I can take some time to try it out and check out the logs...

**Comment by gwenn** [comment]
I can install many apps without admin rights (GVim, Visual Studio Code, Clion, rustc, cargo, MinGW, alacritty, wezterm, ...).

**Comment by schungx** [comment]
Hhmmm.... that seem strange.  In that case Windows Terminal shouldn't be blocked...

You can install it via an installer instead of from the Microsoft Store and it may work...

**Comment by schungx** [comment]
> @schungx If you want, you can checkout https://github.com/gwenn/rustyline/tree/bracketed_paste and then check if you find `UnknownEscSeq` or `Esc` in your logs while running [RUST_LOG=rustyline=debug cargo run --example example 2> debug.log](https://github.com/gwenn/rustyline/blob/bracketed_paste/examples/example.rs#L82). If yes, we will need to catch these [escape sequences](https://github.com/gwenn/rustyline/blob/bracketed_paste/src/tty/unix.rs#L409-L410) and handle them properly.

Tried it, and the example seems to work!!!

No `UnknownEscSeq` or `Esc`.

[debug.log](https://github.com/kkawakam/rustyline/files/8004273/debug.log)

Log attached.

**Comment by schungx** [comment]
Do I need to do any of that `MatchingBracketHighlighter::new()` stuff in my own app in order for this to work?

Can I just set `config.bracketed_paste(true).build()`?

**Comment by gwenn** [comment]
> Tried it, and the example seems to work!!!
> 
> No `UnknownEscSeq` or `Esc` anywhere in the log. Does that mean that Windows Terminal does not send the bracketed paste escape codes to the app?

If you don't have `UnknownEscSeq` or `Esc` anywhere in the log then braketed paste doesn't work...

**Comment by gwenn** [comment]
> If I take away `MatchingBracketHighlighter` it no longer takes multiple lines as a whole, but processes them separately line by line.

It seems related to [this](https://github.com/kkawakam/rustyline/blob/master/src/edit.rs#L339) optim.
Just send me a minimal example to reproduce the issue.

**Comment by schungx** [comment]
As a matter of fact, after scanning through the code, I don't think escape codes are ever implemented for Windows.

Things like color are implemented on Windows via a Highlight Validator, while they are directly implemented on Unix.

So on Windows it is not bracketed paste, but using a validator to continue lines.

I'll experiment some more and post here.  It seems that Windows Terminal has never sent the bracketed paste escape codes to the app.  Maybe there is a switch or option I need to turn on...

**Comment by schungx** [comment]
Taking cue from https://github.com/microsoft/terminal/issues/12385

By setting ENABLE_VIRTUAL_TERMINAL_INPUT for console mode, the escape sequences now properly show up.

**Comment by schungx** [comment]
PR https://github.com/gwenn/rustyline/pull/1 opened with an implementation that works for me!

**Comment by schungx** [comment]
Understand that the implementation is not optimal (which duplicates many of the same escape-code processing for Unix).

It is left in my fork for now: https://github.com/schungx/rustyline

Whoever needs it can pull from my fork, or wait for official support to land here.  I can't guarantee that everything works seamlessly, but at least it works for me...
