### ISSUE TITLE
Need ability to specify which file descriptor should be used for input?

### ISSUE THREAD

**Issue by n1000** [kkawakam/rustyline#599]
I believe the ability to swap out what FD to use for input is needed in cases where the program using rustyline is having its stdin redirected from a file. In these cases, rustyreadline needs to use a FD still connected to the terminal to read input from, instead of using FD=0...

I was looking at this issue: https://github.com/PaulJuliusMartinez/jless/issues/7 (note that I have no affiliation with this project)

And noticed that src/tty/unix.rs directly refered to STDIN_FILENO, without support for passing in / using another FD (such as a fd pointing to /dev/tty).

This seems to sort of be related to https://github.com/kkawakam/rustyline/issues/542 (but this would be a simpler change).

A hacked up version of what this might look like is here: https://github.com/kkawakam/rustyline/compare/master...n1000:configurable_input?expand=1

I'm a Rust beginner, so I mostly worked on this to try and further my learning... The changes above are a hack, but demonstrate the concept. I've realized it's time to go back and reread some parts of "Programming Rust"... :)

It may also be the case that some much simpler solution to this exists, and no change in rustyline is needed...

**Comment by gwenn** [comment]
For reference:
* https://github.com/wez/wezterm/blob/main/termwiz/src/terminal/unix.rs#L248-L253
* https://github.com/wez/wezterm/blob/main/termwiz/src/terminal/windows.rs#L630-L635

**Comment by PaulJuliusMartinez** [comment]
I had considered filing a bug for this, but I believe it can be handled on the user's side by using [`freopen`](https://linux.die.net/man/3/freopen), based on [this StackOverflow post](https://stackoverflow.com/questions/29689034/piped-stdin-and-keyboard-same-time-in-c). I haven't had a chance to test this out yet though.

Even if this does work, I think allowing for some configuration of the input file descriptor, or just supporting a toggle to read from `/dev/tty` makes sense.

**Comment by n1000** [comment]
> For reference:
> 
>     * https://github.com/wez/wezterm/blob/main/termwiz/src/terminal/unix.rs#L248-L253
> 
>     * https://github.com/wez/wezterm/blob/main/termwiz/src/terminal/windows.rs#L630-L635

Thanks, updated src/tty/windows.rs to use "CONIN$" instead of "CON:", and also opened it with both read and write permissions (otherwise was getting a access denied when attempting to call SetConsoleMode()). Did a quick test in a Windows VM, and seems to work.

> I had considered filing a bug for this, but I believe it can be handled on the user's side by using [freopen](https://linux.die.net/man/3/freopen), based on [this StackOverflow post](https://stackoverflow.com/questions/29689034/piped-stdin-and-keyboard-same-time-in-c). I haven't had a chance to test this out yet though.

Agree on this, but unfortunately there also may be some difficulty using freopen, based on this PR: https://github.com/rust-lang/libc/issues/7 . I think that issue is still unresolved based on my searching so far (but I may have missed something also).

**Comment by PaulJuliusMartinez** [comment]
I [was able to use `freopen`](https://github.com/PaulJuliusMartinez/jless/pull/32/files#diff-b28dbadb7b0fb54a6a72860d79ba4fa2c1228788e81a14dbd99f8536f5e317a9R17-R21) to get around this, but, as mentioned by @n1000, had to bring in an [external crate](https://crates.io/crates/libc-stdhandle) to get a reference to the `FILE *` associated with `stdin`.

**Comment by gwenn** [comment]
Could you please give a try to [this](https://github.com/gwenn/rustyline/tree/dev_tty) branch ?
```rust
let config = Config::builder()
        .behavior(Behavior:: PreferTerm)
        .build();
let mut rl = Editor::with_config(config);
```
Like `Haskeline`, with `PreferTerm` behavior, `/dev/tty` is used both for input and output on unix platform.
By default, `rustyline` keeps using stdin / stdout.
Thanks.

**Comment by n1000** [comment]
Works fine for me on Linux (did not try out Windows).

**Comment by gwenn** [comment]
Version 10.0.0 released.
