### ISSUE TITLE
How do I use rustyline in full-duplex mode?

### ISSUE THREAD

**Issue by vi** [kkawakam/rustyline#600]
How do I print new message at the same time as user is typing something in the buffer?
Can `rustyline` be used to implement a chat application or [`rlwrap(1)`](https://linux.die.net/man/1/rlwrap) analogue?
Shall `Editor` expose some handle to allow forcibly redrawing unfinished line after printing something to stdout (behind `rustyline`'s back) or shall `rustyline` also handle printing lines, not just inputting them?

**Comment by gwenn** [comment]
> How do I print new message at the same time as user is typing something in the buffer?
See #235
Like [replxx](https://github.com/AmokHuginnsson/replxx/blob/master/examples/cxx-api.cxx#L55)

**Comment by gwenn** [comment]
Version 10.0.0 released.
