### ISSUE TITLE
rustyline overwrites previously registered SIGWINCH handler

### ISSUE THREAD

**Issue by PaulJuliusMartinez** [kkawakam/rustyline#606]
If an application registers a SIGWINCH handler prior to initializing rustyline, rustyline will override it when it installs its own SIGWINCH handler. Installation of the SIGWINCH handler takes place [here](https://github.com/kkawakam/rustyline/blob/master/src/tty/unix.rs#L1045-L1050).

The [`sigaction`](https://linux.die.net/man/2/sigaction) system call can return the function pointer for the previously registered signal handler. rustyline could store this value and call the function if it is non-NULL. (See [this StackOverflow question](https://stackoverflow.com/questions/17102919/is-it-valid-to-have-multiple-signal-handlers-for-same-signal).) The alternative for the application is to register their signal handler after initializing rustyline and either save the reference to rustyline's signal handler, or leave rustyline's signal handler abandoned, but people probably don't expect rustyline to install a SIGWINCH handler, so they'll only realize this once it causes [a bug](https://github.com/PaulJuliusMartinez/jless/issues/62).

**Comment by gwenn** [comment]
Should we use [signal-hook](https://crates.io/crates/signal-hook) ?

**Comment by gwenn** [comment]
Version 10.0.0 released.
