### ISSUE TITLE
Being able to bind Shift+Enter to something else

### ISSUE THREAD

**Issue by ghigt** [kkawakam/rustyline#653]
While this works in the example folder:
```rust
rl.bind_sequence(
    KeyEvent(KeyCode::Char('s'), Modifiers::CTRL),
    EventHandler::Simple(Cmd::Newline),
);
```
This is handled by the default `Enter` behavior:
```rust
rl.bind_sequence(
    KeyEvent(KeyCode::Enter, Modifiers::SHIFT),
    EventHandler::Simple(Cmd::Newline),
);
```
Is it expected or is it a bug?

**Comment by gwenn** [comment]
On Windows, it may be possible.
But on Unix, by default, there is no way to make the distinction between SHIFT-Enter / CTRL-Enter and Enter.
See https://unix.stackexchange.com/questions/536352/ctrl-enter-shift-enter-and-enter-are-interpreted-as-the-same-key

**Comment by patrik-simunic-cz** [comment]
Well..... how does the Node REPL handle this then?
Since it's working in there, there obviously has to be a way to distinguish between `Enter` and `SHIFT`+`Enter`(?)

**Comment by gwenn** [comment]
https://github.com/kkawakam/rustyline/issues/744
