### ISSUE TITLE
How to access LineBuffer?

### ISSUE THREAD

**Issue by rtfeldman** [kkawakam/rustyline#656]
Thanks for making rustyline! I've been enjoying it.

I see the docs for [`LineBuffer`](https://docs.rs/rustyline/10.0.0/rustyline/line_buffer/struct.LineBuffer.html) but I can't seem to find a way to obtain one. Looking through the source, it seems none of its usages are exposed (that I can tell), but `LineBuffer` itself is exposed, which makes me think there's some way to access it...I just can't figure out what it is!

**Comment by gwenn** [comment]
Currently, the only place where you access the `LineBuffer` is [here](https://github.com/kkawakam/rustyline/blob/master/src/completion.rs#L92-L95).
=> https://docs.rs/rustyline/latest/rustyline/completion/trait.Completer.html#method.update
We may add something like replxx [modify_callback](https://github.com/AmokHuginnsson/replxx/blob/master/include/replxx.h#L235-L255).
