### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by figsoda** [kkawakam/rustyline#664]
The latest version of rustyline with fuzzy feature enabled depends on an outdated version of `skim`, which pulls in an oudated version of `nix` with CVEs: https://github.com/advisories/GHSA-76w9-p8mg-j927, https://github.com/advisories/GHSA-wgrg-5h56-jg27. It would be nice if there is a new release with more up-to-date dependencies

**Comment by gwenn** [comment]
Version 10.1.0 released.
