### ISSUE TITLE
v10.1.0 increases the MSRV to 1.62

### ISSUE THREAD

**Issue by daxpedda** [kkawakam/rustyline#671]
https://github.com/kkawakam/rustyline/pull/662 uses `derive(Default)` on enums, which is only supported since 1.62.
Personally I don't have a stake in supporting old MSRV's, but it broke CI's on projects I'm working on.

Cc @kevinlewi, I assume you have a stake in this.

**Comment by gwenn** [comment]
https://doc.rust-lang.org/clippy/configuration.html#specifying-the-minimum-supported-rust-version ?

**Comment by daxpedda** [comment]
Maybe there is a misunderstand there.
The crate `rustyline` **cannot** be used with Rust versions lower then 1.62 because it uses the `#[derive(Default)]` on enums feature.

Yes, the Clippy configuration you posted would be useful to add to `rustyline` to prevent this problem in the future.
I can make a PR.

**Comment by gwenn** [comment]
But currently there is no MSRV defined for `rustyline`.
We only define [edition = "2018"](https://github.com/kkawakam/rustyline/blob/master/Cargo.toml#L5).
So I guess MSRV should be <= 1.55.0 (edition "2021 = version 1.56.0).

**Comment by gwenn** [comment]
Except that `env_logger` version 0.10.0 as an MSRV = 1.60.0.
So https://github.com/kkawakam/rustyline/commit/5abc48df15d713e7e87cc5591e4cfbdb9168614a should also be rollbacked.

**Comment by daxpedda** [comment]
I guess this is a request to add an MSRV to `rustyline` then?
Would it be possible to make a new release with the MSRV branch?

**Comment by gwenn** [comment]
https://github.com/kkawakam/rustyline/releases/tag/v10.1.1
https://crates.io/crates/rustyline/10.1.1

**Comment by daxpedda** [comment]
Thank you for the prompt handling of all this :heart:.

**Comment by gwenn** [comment]
4 days since 10.1.0 release...
And sorry for all the troubles.
