### ISSUE TITLE
MSRV policy

### ISSUE THREAD

**Issue by daxpedda** [kkawakam/rustyline#673]
Considering https://github.com/kkawakam/rustyline/issues/581 and https://github.com/kkawakam/rustyline/issues/671 it might be useful to introduce an official MSRV policy.

**Comment by gwenn** [comment]
I would prefer not to have a MSRV.
Allow any incompatibility in major releases.
But, make sure that minor releases don't break X ? X = stable Rust version used by previous release ?
Because it is easier to follow only stable Rust releases.
See https://github.com/rusqlite/rusqlite/issues/566

**Comment by daxpedda** [comment]
That's a common MSRV policy.
E.g. https://github.com/RustCrypto/traits/tree/master/elliptic-curve#minimum-supported-rust-version.

Sounds good to me.

**Comment by gwenn** [comment]
Even minor releases can change MSRV ?
But still, you need to check patch releases...

**Comment by daxpedda** [comment]
I'm a bit confused, do you want to keep the MSRV between patch releases or minor releases?

But yeah, you are not gonna be able to enforce it without setting up checks in CI probably.

In any case, any MSRV policy is better then none, even if you don't want to follow any MSRV at all.

**Comment by reneleonhardt** [comment]
Release 17 seems to correspond to MSRV 1.82.0.
It would be great to publish it instead of all library users having to compile and try for themselves with tools like cargo-msrv.
