### ISSUE TITLE
Re: Thanks for the detailed bug report.

### ISSUE THREAD

**Issue by schwidom** [kkawakam/rustyline#707]
Thanks for the detailed bug report.

_Originally posted by @gwenn in https://github.com/kkawakam/rustyline/issues/705#issuecomment-1604476988_
            
Thanks for the fix. 

How long does it normally take that a fix is available in the cargo repository?
Is it needed to increase the patch number for that?

Regards, 
Frank

**Comment by gwenn** [comment]
I will try to push a new release this week-end.
And it will be a major version because of previous changes (mostly because I am not confident that there is no breaking change)...

**Comment by schwidom** [comment]
At least you have a decent test suite.
