### ISSUE TITLE
Could `Validator` also take the cursor position?

### ISSUE THREAD

**Issue by segeljakt** [kkawakam/rustyline#712]
If I give this input to my rustyline REPL (`|` is cursor):

```
>> if b { f() } else { f() }|
```

I have currently implemented that `<Enter>` evaluates the statement. I did this validating that the current line ends with `}`, and if so, yields `ValidationResult::Valid` and otherwise `ValidationResult::Incomplete`. However, if my cursor is here:

```
>> if b { f() } else {|}
```

I would like `<Enter>` to insert a newline:

```
>> >> if b { f() } else {
|}
```

This requires me to know the position of the cursor, but since `validate` only takes an input this is not possible:
```rust
impl Validator for MyValidator {
    fn validate(&self, ctx: &mut ValidationContext) -> Result<ValidationResult> {
        let input: &str = ctx.input();
        // ...
    }
}
```
Would it be feasible to extend `Validator` with this functionality?

**Comment by segeljakt** [comment]
Oh, nice. Thanks

**Comment by segeljakt** [comment]
Alright I managed to get it working 👍 
```rust
pub(crate) struct BraceValidator;

impl ConditionalEventHandler for BraceValidator {
    fn handle(
        &self,
        evt: &rustyline::Event,
        n: rustyline::RepeatCount,
        positive: bool,
        ctx: &rustyline::EventContext,
    ) -> Option<rustyline::Cmd> {
        if ctx.line().ends_with('}') && ctx.pos() == ctx.line().len() {
            return Some(rustyline::Cmd::AcceptLine);
        } else {
            return None;
        }
    }
}

fn main() {
    let mut rl = Editor::<Repl, FileHistory>::new()?;

    rl.bind_sequence(
        KeyEvent::new('\r', Modifiers::NONE),
        EventHandler::Conditional(Box::new(BraceValidator)),
    );
}
```

**Comment by gwenn** [comment]
Good question !

**Comment by segeljakt** [comment]
It works on macOS but I'm not sure how other platforms handle it. Maybe it's the same

**Comment by gwenn** [comment]
In fact, there is a simpler solution than the `ConditionalEventHandler`:
https://docs.rs/rustyline/latest/rustyline/enum.Cmd.html#variant.AcceptOrInsertLine
=> `accept_in_the_middle` should be false.
(Sorry I forgot...)
And you want to overwrite these bindings:
https://github.com/kkawakam/rustyline/blob/aecbf41252b22c4e19785342073c5695a56c4d2b/src/keymap.rs#L1050-L1052

**Comment by gwenn** [comment]
See https://github.com/edgedb/edgedb-cli/blob/b4b47021710a2bc425ba1a676eec704681b7fae7/src/migrations/prompt.rs#L80C1-L81

**Comment by gwenn** [comment]
And you should be able to use https://docs.rs/rustyline/latest/rustyline/enum.KeyCode.html#variant.Enter instead of `'\r'`...

**Comment by gwenn** [comment]
Sorry for the messy API.

**Comment by segeljakt** [comment]
Your solution works really nice, thanks 👍
