### ISSUE TITLE
How to instantiate ChangeSet?

### ISSUE THREAD

**Issue by kamiyaa** [kkawakam/rustyline#713]
So it can be used in `rustyline::completion::Completer::update()` ?

**Comment by gwenn** [comment]
Currently, only `rustyline` can.
This change was introduced by #666

**Comment by kamiyaa** [comment]
How does someone use `rustyline::completion::Completer::update()` then?

**Comment by gwenn** [comment]
You can implement `update`.
But you are not supposed to use / call it!
Only `rustyline` should call it.

**Comment by kamiyaa** [comment]
Resolved. Was migrating from v9 to v12.

v9 code:
```rust
completer.update(line_buffer, pos, &my_string);
```

v12 code:
```rust
line_buffer.set_pos(pos);
line_buffer.kill_buffer(listener);
line_buffer.insert_str(pos, &my_string, listener);
line_buffer.move_end();
```
