### ISSUE TITLE
rustyline break some architecture on linux

### ISSUE THREAD

**Issue by eatradish** [kkawakam/rustyline#731]
The reason for this is that some of the terminal control constants in `termios` are wrong in some architectures, specifically at: https://github.com/dcuddeback/termios-rs/pull/37 but it looks like the termios authors don't show up much anymore, rustlyline Is it possible to fix the problem on your own code? The solution is simple: change all variables like `termios::VEOF` to `libc::VEOF`

**Comment by gwenn** [comment]
Maybe we should rollback #717 ?

**Comment by eatradish** [comment]
> Maybe we should rollback #717 ?

Perhaps it could also be maintained by rustyline's author fork a termios? I'm not sure which is the better option

**Comment by gwenn** [comment]
> > Maybe we should rollback #717 ?
> 
> Perhaps it could also be maintained by rustyline's author fork a termios? I'm not sure which is the better option

I would prefer to put `termios-rs` behind an optional feature (and keep using `nix` by default as before).
(I suppose that you can activate `termios-rs` based on OS)

**Comment by sunfishcode** [comment]
If you're interested, another option would be to use rustix's [termios API](https://docs.rs/rustix/latest/rustix/termios/index.html), which doesn't have the issues of https://github.com/nix-rust/nix/issues/2071 or https://github.com/dcuddeback/termios-rs/pull/37.

**Comment by gwenn** [comment]
@sunfishcode
But possibly `rustix` specific issues...

**Comment by gwenn** [comment]
[nix termios usages](https://github.com/search?q=lang%3Arust+%22use+nix%3A%3Asys%3A%3Atermios%22&type=code)
=> 702
[rustix termios usages](https://github.com/search?q=lang%3Arust+%22use+rustix%3A%3Atermios%22&type=code)
=> 36
