### ISSUE TITLE
Paste `<cmd-v>` does not put cursor at end of line

### ISSUE THREAD

**Issue by segeljakt** [kkawakam/rustyline#732]
If I have a REPL with my cursor here:
```
>> |
```
and I press `<cmd-v>` (on macOS) with the text `foo` in my clipboard, I get:
```
>> fo|o
```
but I would expect this:
```
>> foo|
```
Is it a bug or do I need to configure something in Rustyline to achieve this behaviour?

**Comment by gwenn** [comment]
Cannot reproduce:
```sh
cargo run --example minimal
> foo
```

**Comment by gwenn** [comment]
Version 18.0.0 released
