### ISSUE TITLE
Windows (11) line wrap doesn't line feed for the first line

### ISSUE THREAD

**Issue by BrandonXLF** [kkawakam/rustyline#738]
On Windows 11 (haven't tested 10) line wrapping doesn't line feed when the first line feed should be inserted. Line feeds for subsequent lines are inserted as expected. Only occurs when color mode is enabled (which is on by default).

This seems to be similar to #351. I tested `6.1.2` which resolved #351 but the issue is still present in that version.

**Comment by gwenn** [comment]
Could you please do the following ?
(a) check that you are respecting this rule:
https://docs.rs/rustyline/latest/rustyline/highlight/trait.Highlighter.html
> Currently, the highlighted version must have the same display width as the original input.
(b) check that the provided example has the bug too:
https://github.com/kkawakam/rustyline/blob/master/examples/example.rs#L23-L47
```sh
cargo run --example example
```
(I don't have access to a Windows 11 machine but only a Windows 10, I am going to check)

**Comment by gwenn** [comment]
Cannot reproduce with the old `cmd` shell:
```txt
1> (abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuivwxyz abcdefg
hijklmno)
```

**Comment by BrandonXLF** [comment]
The example `example` works as expected but `minimal` does not.

**Comment by gwenn** [comment]
Same here.
Thanks.

**Comment by gwenn** [comment]
> Only occurs when color mode is enabled (which is on by default).

Indeed, with this local patch, `minimal` example behaves correctly:
```patch
diff --git a/examples/minimal.rs b/examples/minimal.rs
index 9fc627e..d3ff7b0 100644
--- a/examples/minimal.rs
+++ b/examples/minimal.rs
@@ -1,9 +1,12 @@
-use rustyline::{DefaultEditor, Result};
+use rustyline::{ColorMode, Config, DefaultEditor, Result};

 /// Minimal REPL
 fn main() -> Result<()> {
     env_logger::init();
-    let mut rl = DefaultEditor::new()?;
+    let config = Config::builder()
+        .color_mode(ColorMode::Disabled)
+        .build();
+    let mut rl = DefaultEditor::with_config(config)?;
     loop {
         let line = rl.readline("> ")?; // read
         println!("Line: {line}"); // eval / print
```

**Comment by gwenn** [comment]
Ok, the issue must be here:
https://github.com/kkawakam/rustyline/blob/ebbd5c116271a6910c5f9c1e5c61599f36f6cbcd/src/tty/windows.rs#L424-L435

**Comment by gwenn** [comment]
@BrandonXLF Could you please give PR #739 a try ?

**Comment by BrandonXLF** [comment]
> @BrandonXLF Could you please give PR #739 a try ?

Works as expected 👍

**Comment by gwenn** [comment]
Version 13.0.0 released.
