### ISSUE TITLE
Test binding::test::size_of_event fails on i686 / 32 bits arches

### ISSUE THREAD

**Issue by eclipseo** [kkawakam/rustyline#740]
Hello Team,

The following test fails on arch i686:

```
failures:
---- binding::test::size_of_event stdout ----
thread 'binding::test::size_of_event' panicked at src/binding.rs:255:9:
assertion `left == right` failed
  left: 16
 right: 32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    binding::test::size_of_event
test result: FAILED. 176 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.01s
error: test failed, to rerun pass `--lib`
```

Environment:

Rustyline 12.0.0
Rust 1.73
Fedora Linux 40 (Rawhide)

**Comment by blinxen** [comment]
This test fails because the size of `Event` is assumed to be 32, which is only valid for 64bit systems. For 32bit systems the size would be smaller, probably 16bit (maybe more).

**Comment by gwenn** [comment]
https://github.com/kkawakam/rustyline/pull/614
> This has the effect of reducing the size of the Event enum.

So I guess we can check that the size is smaller than or equals to 32.

**Comment by gwenn** [comment]
we can also use this:
https://doc.rust-lang.org/reference/conditional-compilation.html#target_arch
```rust
  #[cfg(target_arch = "x86_64")]
  #[test]
  fn size_of_event() {
    assert_eq!(size_of::<Event>(), 32);
  }
```

**Comment by gwenn** [comment]
Version 13.0.0 released.
