### ISSUE TITLE
diy_hints example code doesn't work

### ISSUE THREAD

**Issue by zahash** [kkawakam/rustyline#741]
diy_hints example code doesn't work. 
Need some nicely written examples to demonstrate auto completion features instead of a hacky mess.

**Comment by AnotherDaniel** [comment]
More specifically, the Completer, Highlighter and Validator traits are private, according to the compiler - trying this with 12.0.0.
Same here, trying to build something using Hints, but the current state of documentation/examples on this topic does make it challenging.

**Comment by gwenn** [comment]
> More specifically, the Completer, Highlighter and Validator traits are private, according to the compiler - trying this with 12.0.0.

https://docs.rs/rustyline/latest/rustyline/completion/trait.Completer.html
> pub trait Completer {

https://docs.rs/rustyline/latest/rustyline/highlight/trait.Highlighter.html
> pub trait Highlighter {

https://docs.rs/rustyline/latest/rustyline/validate/trait.Validator.html
> pub trait Validator {

https://docs.rs/rustyline/latest/rustyline/derive.Completer.html
> Available on crate feature derive only.

**Comment by AnotherDaniel** [comment]
Got it now.
