### ISSUE TITLE
CompletionType::List does not support completion candidates that are shorter than the input

### ISSUE THREAD

**Issue by sharkdp** [kkawakam/rustyline#748]
Thank you for maintaining this crate — we use it in [Numbat](https://github.com/sharkdp/numbat) and it works great.

We want to implement a feature where a user could type something like `\hbar` in the REPL, press <kbd>Tab</kbd> and it would be replaced by `ℏ`. This seems to work fine when using `CompletionType::Circular`, but it does not work for `CompletionType::List`. Words will only be replaced if they are longer than the input. This is probably due to this check:

https://github.com/kkawakam/rustyline/blob/fafa0b9ba7cc6fbd21c055ea06ed42be6504ae62/src/lib.rs#L154

Would it be possible to support this use case?

Remark: that check above should probably use `lcp.unicode_width()` instead of `lcp.len()` (?).

**Comment by gwenn** [comment]
Not strictly related to the issue but to your remark:
> that check above should probably use lcp.unicode_width() instead of lcp.len() (?).

`s.line.pos()` and `start` are byte offsets so the difference between them is a number of bytes.
So `lcp.len()` seems right.
But maybe we should compare `s.line[start..s.line.pos()].width()` and `lcp.width()` instead.
I will try to do some tests...

**Comment by gwenn** [comment]
Could you please give #750 a try ?

**Comment by gwenn** [comment]
Version 13.0.0 released.

**Comment by sharkdp** [comment]
Thank you!
