### ISSUE TITLE
[tty/unix] Do not disable termios signals

### ISSUE THREAD

**Issue by andreistan26** [kkawakam/rustyline#757]
For some use cases the signals should not be disabled, as there is no way to distinguish between `SIGINT` and `SIGQUIT` with the current `Interrupt` enum. 

I am not familiar with the project but as far as i can see there is no way around it. If this is the case, i can open a PR with a fix for adding another config field.

**Comment by gwenn** [comment]
If possible, could you please provide a similar library (not necessarily in Rust) that does ?
And could you please confirm that your issue is related to ISIG here:
https://github.com/kkawakam/rustyline/blob/c01855af1cbfe1f3ded3f7bfbde5efab17a78240/src/tty/unix.rs#L1517
?
Thanks.

**Comment by andreistan26** [comment]
1) I am not very familiar with libraries alike, so i cannot give any examples.
2) Yes the issue is related to `LocalFlags::ISIG"`. Due to the signals not being able to be handled within the interpreter using a signal handler. I am not sure about other the implications of removing `ISIG` via a config option , another solution would be to emit a more specific interrupt like `SpecificInterrupt(SIGINT)`

**Comment by gwenn** [comment]
We may have a look at linefeed / mortal:

**Comment by andreistan26** [comment]
i think that a simple config should do it, much like `mortal`. I will post a draft later

**Comment by andreistan26** [comment]
Is there any way to print the signal specific chars. I would like to have:
- `^C` for ctrl+c
- `^\` for ctrl+\

**Comment by gwenn** [comment]
Version 14.0.0 released
