### ISSUE TITLE
how can I flush the stdout when i use print macro?

### ISSUE THREAD

**Issue by OMObuan** [kkawakam/rustyline#767]
when I tried use ```print!``` macro,it will push the output into the cache,I wanted to show it immediately,so I use ```io::stdout().flush().unwrap()```,but it didn't work,and even clear my output(if i don't call it,it will print when the program exit),i also tried ```println!```,it will work well.If I don't use rustyline,both of them can do it correctly.I guess maybe rustyline do something to the output cache,but i didn't find any docs of this.If anyone can help,I will appreciate it!

**Comment by gwenn** [comment]
Without a complete minimal example, I can only guess.
You are not suppose to use stdout while `rustyline` is reading.
You should use an `ExternalPrinter` instead:
https://docs.rs/rustyline/latest/rustyline/trait.ExternalPrinter.html
But as far as I know, `rustyline`doesn't lock the `stdout` so I am not sure.

**Comment by gwenn** [comment]
There is this option:
https://docs.rs/rustyline/latest/rustyline/config/struct.Config.html#method.check_cursor_position
