### ISSUE TITLE
Logging visible when using `env_logger`

### ISSUE THREAD

**Issue by mcdearman** [kkawakam/rustyline#774]
When I enable logging with `env_logger` I can see all of the rustyline logs. This wouldn't a problem if it didn't make it unusable. Can you hide those for the published crate?

**Comment by gwenn** [comment]
https://docs.rs/env_logger/latest/env_logger/#enabling-logging
> By default all logging is disabled except for the error level

...
> RUST_LOG=error,hello=off turn on global error logging, but turn off logging for hello

```
RUST_LOG=...,rustyline=off
```
