### ISSUE TITLE
Add a way to enable command repeat

### ISSUE THREAD

**Issue by Yamakaky** [kkawakam/rustyline#78]
Like in gdb. Imagine you enter `step`. If after that you press enter with an empty command line, it will repeat `step`. It's really handy for debuggers for example. It would not be used in all cli interfaces, though.

**Comment by gwenn** [comment]
Could you please confirm that the only thing you need is access to the last/previous history entry ?
```rust
    /// Return the last history entry
    pub fn last(&self) -> Option<&String> {
        self.entries.back()
    }
```

```rust
         let readline = rl.readline(PROMPT);
         match readline {
             Ok(line) => {
                  if line.is_empty() {
                      let last = rl.get_history().last();
                      println!("Last: {:?}", last);
                  }
```

**Comment by Yamakaky** [comment]
Yeah. I do it [that way](https://github.com/Yamakaky/dcpu/blob/master/src/emulator/debugger/mod.rs#L61-L71), but it could be builtin as some other projects may need it.
