### ISSUE TITLE
multiline support

### ISSUE THREAD

**Issue by danburkert** [kkawakam/rustyline#79]
The README mentions multiline support, but I can't find a way to enable it.  Is this feature implemented?

**Comment by gwenn** [comment]
Multiline support is enabled by default and there is currently no way to disable it.

**Comment by hayd** [comment]
How do you enter a multiple line entry? Following the example in the readme...

I was imaging shift+Enter but nothing jumps out in the README, and is there a way to force multiline e.g. if there are open parenthesis?

**Comment by gwenn** [comment]
I guess you want https://github.com/kkawakam/rustyline/issues/153.
But `multiline support` in the README means https://github.com/antirez/linenoise#single-line-vs-multi-line-editing or [horizontal-scroll-mode=off](https://tiswww.case.edu/php/chet/readline/rluserman.html) or `set wrap` with vim.

**Comment by hayd** [comment]
Is there an example of implementing this with rustyline, or does "do it by yourself" mean "not with rustyline"?

**Comment by gwenn** [comment]
Currently, there is no example here but in a dependent crate:
https://github.com/kyren/rlua/blob/master/examples/repl.rs#L40

**Comment by RadicalZephyr** [comment]
In case anybody here is interested, I'm working on true multi-line editing support in #182.  Feedback on the proposed API is very much appreciated.

**Comment by gwenn** [comment]
Fixed in version 6.0.0
