### ISSUE TITLE
Doc missing: What happens if history file does not exist?

### ISSUE THREAD

**Issue by matthiasbeyer** [kkawakam/rustyline#80]
If I `load_history()` from a `PathBuf` that does not point to an existing file - what happens?

The information is missing in the documentation.

**Comment by Yamakaky** [comment]
It returns a https://docs.rs/rustyline/1.0.0/rustyline/type.Result.html, which can contains a io::Error.

**Comment by matthiasbeyer** [comment]
@Yamakaky Yep, that's exactly what I feared. I expected it to create the file... but as you say it does not. So I have to fix my code because the docs for this are missing. :smile: You see what I mean?

**Comment by Yamakaky** [comment]
Well, it creates it on `save_history()`, isn't is sufficient?

**Comment by matthiasbeyer** [comment]
Nope, as one calls `load_history()` _before_ `safe_history()`, ... IMO.

**Comment by Yamakaky** [comment]
Do you really need to create the file yourself? I personnaly do https://github.com/Yamakaky/dcpu/blob/master/src/emulator/debugger/mod.rs#L49-L56
