### ISSUE TITLE
Relation between rustyline and crossterm

### ISSUE THREAD

**Issue by soywod** [kkawakam/rustyline#805]
I am looking for a [`crossterm`](https://docs.rs/crossterm/latest/crossterm/index.html) prompt widget, following the readline standard. If you understood well, `rustyline` implements its own standard regarding terminal manipulation, right? If so, having both `crossterm` and `rustyline` dependencies does not make sens and I may have to implement a `crossterm` widget from scratch, based on your work. I just want to be sure before starting anything.

**Comment by gwenn** [comment]
You should first check [reedline](https://github.com/nushell/reedline) which uses crossterm.
Or you might be able to implement [this](https://github.com/kkawakam/rustyline/blob/547a9a0c3b82d5d8e88242b451bc36d38687a3e1/src/tty/mod.rs#L220) private trait using crossterm (by forking rustyline).

**Comment by soywod** [comment]
`reedline` is what I needed, thank you!
