### ISSUE TITLE
Add an Iterator

### ISSUE THREAD

**Issue by Yamakaky** [kkawakam/rustyline#82]
We could do:

``` rust
for cmd in editor {
    match ...
}
```

It would end on EOF or <C-d>

**Comment by gwenn** [comment]
And for \<C-c\> ?

**Comment by Yamakaky** [comment]
In [my code](https://github.com/Yamakaky/dcpu/blob/master/src/emulator/debugger/mod.rs), I ignore it. It's handy if you want to discard the current line. `python` does it.

**Comment by gwenn** [comment]
Something like:
```rust
impl<C: Completer> Iterator for Editor<C> {
    type Item = Result<String>;

    fn next(&mut self) -> Option<Result<String>> {
        let readline = self.readline(""); // FIXME prompt
        match readline {
            l @ Ok(_) => Some(l),
            Err(error::ReadlineError::Eof) => None,
            e @ Err(_) => Some(e),
        }
    }
}
```
?

**Comment by Yamakaky** [comment]
Yeah, something like that. The prompt could be configured at creation time, since it tend to stay the same for most program. You should also keep the current interface, in case someone want to do something different

**Comment by Yamakaky** [comment]
SGTM. Just add an implementation for `IntoIterator` for extra convenience ^^

**Comment by gwenn** [comment]
2.0 released
