### ISSUE TITLE
Send prompt to stdout even if stdin is not a tty or check TERM also on Windows

### ISSUE THREAD

**Issue by jasagredo** [kkawakam/rustyline#832]
This issue arises from the investigation in https://github.com/mthom/scryer-prolog/issues/2694. There is a comment at the end explaining my conclusions but I will re-word it here below.

I was having issues calling Scryer Prolog from emacs. Scryer Prolog uses rustyline for the repl, and it will print a prompt on the repl (`?- `). The emacs package `ediprolog` expects that prompt for running.

On Linux, the emacs shell `eshell` is identified by rustyline as an unsupported terminal, as it sets `TERM=dumb`. There `rustyline` [flushes the prompt to stdout](https://github.com/kkawakam/rustyline/blob/5b92355961718474fb67a84ae1520cbd75368f3d/src/lib.rs#L653-L660).

On Windows, the emacs shell `eshell` also sets `TERM=dumb` but this is not checked (it is said that [checking `TERM` on Windows is a no-op](https://github.com/kkawakam/rustyline/blob/5b92355961718474fb67a84ae1520cbd75368f3d/src/tty/windows.rs#L722-L725), not sure why) so it falls into [the third case of `readline_with`](https://github.com/kkawakam/rustyline/blob/5b92355961718474fb67a84ae1520cbd75368f3d/src/lib.rs#L673-L677) which does not flush the prompt.

I think at least with MSYS2 and others it is becoming more common for Windows applications to use things like `TERM=dumb` so I guess the check for "unsupported terminals" could be run also on Windows?

**Comment by gwenn** [comment]
For [is_unsupported](https://github.com/kkawakam/rustyline/blob/5b92355961718474fb67a84ae1520cbd75368f3d/src/tty/windows.rs#L722-L725), we need to check the behavior of other similar libraries but your proposal seems right.
For MSYS2, see #401.

**Comment by gwenn** [comment]
Both [replxx](https://github.com/AmokHuginnsson/replxx/blob/1f149bfe20bf6e49c1afd4154eaf0032c8c2fda2/src/replxx_impl.cxx#L638) and [isocline](https://github.com/daanx/isocline/blob/c9310ae58941559d761fe5d2dd2713d245f18da6/src/isocline.c#L538) seem to behave like you suggested: no distinction between unix and windows.

**Comment by gwenn** [comment]
Could you please give a try to PR #834 ?
Thanks.

**Comment by jasagredo** [comment]
Thanks @gwenn !
