### ISSUE TITLE
Do a release

### ISSUE THREAD

**Issue by Yamakaky** [kkawakam/rustyline#89]
Last one was in August, there are some neat unreleased features!

**Comment by kkawakam** [comment]
Yea, I am planning on pushing out a release soon.  I started looking through all the changes that have been made and there have been several API breaking changes.  It would seem strange to push out another major version so close to the last major release.  I can add back-in backwards compatibility for the time being since the scope of the breakages was pretty limited but I'm gonna have to think about it.

**Comment by nicklan** [comment]
Just wanted to ping on this.  There's some unreleased stuff I'd love to use. 

Is it reasonable to target master for a new project and assume the next release will mostly have that api?

**Comment by blanham** [comment]
It's been another month, is this repo dead?

**Comment by vinc** [comment]
It'd be good to have a new release of this project, especially with more recent dependencies.

**Comment by kpcyrd** [comment]
I'm currently blocked by outdated dependencies as well, the rustyline version on crates.io doesn't compile for `mips-unknown-linux-musl` while git master does.

**Comment by andygrove** [comment]
Looks like this project is no longer maintained?

**Comment by andygrove** [comment]
Since there hasn't been a release in almost 2 years I went ahead and forked the repo and published a release since I depend on this to release my project.

https://crates.io/crates/rustyline-nightly

I hope that helps some others too.

**Comment by mssun** [comment]
@andygrove Thanks.

Also, try to ping @Yamakaky to do a release.

**Comment by brendanzab** [comment]
Oh nice, I've been waiting on https://github.com/kkawakam/rustyline/issues/123#issuecomment-405095599 - can we possibly get another person onto the crates.io ownership too?

**Comment by gwenn** [comment]
I asked @kkawakam to add me as owner on crates.io.
Be prepared for a new release soon, two years on from 1.0 release...
Beta testers/feedback welcome.

**Comment by gwenn** [comment]
2.0 released
