### ISSUE TITLE
Support IME?

### ISSUE THREAD

**Issue by hh9527** [kkawakam/rustyline#92]
I like this great project, but it seemed IME is not supported for now (at least in Windows).

**Comment by kkawakam** [comment]
I'm sorry,  what are you referring to when you say IME?

**Comment by hh9527** [comment]
IME is the Input Method Engine/Module, which is for input non-western character text, see following screenshot:
<img width="523" alt="2016-10-31 10 50 55" src="https://cloud.githubusercontent.com/assets/3439410/19858510/b136d8a0-9fbc-11e6-963b-e947d8d60395.png">

**Comment by hh9527** [comment]
Oh, my mistake, I use a wrong page code, and that cause the IME disabled.
